### ISSUE TITLE
Combat Flight Simulator 2

### ISSUE THREAD

**Issue by IllustriousProsperus** [narzoul/DDrawCompat#383]
With "DDrawCompat-v0.5.4" the cockpit **is not visible**.
The black rectangle seems to be some function that is not visible even with the radeon (with the video card without ddraw it is not possible to activate 3D hw acceleration)

**_DgVoodoo2 2.82.3, visibile cockpit, map with a black rectangle inside_**
![Screenshot (75)](https://github.com/user-attachments/assets/b5649adf-e723-4be0-9363-04b916455b16)

**_DDrawCompat-v0.5.4 Invisible cockpit, map without the black rectangle_**
![Screenshot (76)](https://github.com/user-attachments/assets/4e1eb1a2-6d2a-4376-b246-2aad9cdee8f3)

**_DDrawCompat-v0.5.4 visible cockpit in windowed mode, map with the black rectangle_**

![CSF2](https://github.com/user-attachments/assets/fb6a722d-44c0-4290-9022-abdfa54f2457)

**Comment by git-hub-MY** [comment]
Sounds like something Sprite Detection=zconst may work with?

Problems like white borders on 2D maps in other games I fixed by FontAliasing,

**Comment by narzoul** [comment]
> With "DDrawCompat-v0.5.4" the cockpit is not visible

I can't reproduce this issue.

> The black rectangle seems to be some function that is not visible even with the radeon (with the video card without ddraw it is not possible to activate 3D hw acceleration)
> 
> DgVoodoo2 2.82.3, visibile cockpit, map with a black rectangle inside

That black rectangle looks more like a dgVoodoo bug. I don't see it on 3rd party screenshots of the game either, e.g.:
https://www.mobygames.com/game/2574/microsoft-combat-flight-simulator-2-ww-ii-pacific-theater/screenshots/

**Comment by IllustriousProsperus** [comment]
> > With "DDrawCompat-v0.5.4" the cockpit is not visible
> 
> I can't reproduce this issue.
> 
> > The black rectangle seems to be some function that is not visible even with the radeon (with the video card without ddraw it is not possible to activate 3D hw acceleration)
> > DgVoodoo2 2.82.3, visibile cockpit, map with a black rectangle inside
> 
> That black rectangle looks more like a dgVoodoo bug. I don't see it on 3rd party screenshots of the game either, e.g.: https://www.mobygames.com/game/2574/microsoft-combat-flight-simulator-2-ww-ii-pacific-theater/screenshots/

with the ddraw from braveheart and HG1 the black rectangle is still present (it's the map). With ddraw from hg1 the the initial loading is slower (

hg1 ddraw

https://github.com/user-attachments/assets/7102431f-0a22-4dee-8c38-ed8b3f1d4683

braveheart ddraw

https://github.com/user-attachments/assets/d8dadc15-f127-402b-95bf-4b0ab8eff98f

I tried some settings but it seems the main menu cannot be displayed in full screen and the splash screen is "cut" in half

**Comment by narzoul** [comment]
> with the ddraw from braveheart and HG1 the black rectangle is still present (it's the map)

Are you talking about windowed mode? I don't have a black rectangle there either. Did you install some patches or mods or something? I'm starting to think we're not testing the same version of the game.

> With ddraw from hg1 the the initial loading is slower

Doesn't matter, I will discard that solution anyway, it creates worse problems than it solves. I have since found an alternative workaround.

> I tried some settings but it seems the main menu cannot be displayed in full screen

For me it remembers the last state after pressing alt+enter. It either loads in windowed mode or fullscreen mode depending on what was last used before exiting the game.
If it doesn't go into fullscreen with alt+enter, please share debug logs of pressing alt+tab in the menu.

> and the splash screen is "cut" in half

Cannot reproduce... although I've seen similar problems with splash screens in other games. GDI interworking issue probably. Low prio, not terribly interested in checking it for the time being.

**Comment by IllustriousProsperus** [comment]
I did some tests and...

in **_windowed mode_** whatever resolution/color depth you choose the rectangle/map will be black

in **_fullscreen mode and d3d enabled only_** if you choose any resolution/depth up to "1760x990" color the rectangle/map will be visible, if you choose "1920x1080x16bit" the map will still be visible, if you choose "1920x1080x32bit" the map will NOT be visible anymore (tested with HG1 ddraw build, with the braveheart ddraw build it doesn't work)


Now for some reason when you want start a "rapid flight" the game tends to crash

https://wormhole.app/jZXzB#YiLZmcnFF1WH1Te6V_UZFw

the splash screen is visible correctly in fullscreen only

the black rectangle disappeared but I can't see the elements

with the latest build of HG1 the cockpit is now always visible (fullscreen mode only), but if you change the view from 2d to 3d it happens as in the image and if you go back with the 2d cockpit the graphic problem disappears

![Image](https://github.com/user-attachments/assets/010778ef-8ffd-42a8-80b8-d2a1d77524ea)

![Image](https://github.com/user-attachments/assets/57eff5a1-0d4d-4f37-a0f0-e0280f80b4c3)

**Comment by narzoul** [comment]
Please retest this with v0.6.0 and let me know which issues you're still experiencing.

**Comment by IllustriousProsperus** [comment]
> Please retest this with v0.6.0 and let me know which issues you're still experiencing.

No changes, I noticed that the game tends to crash often with Win11 24h2 (with win 10 it was more stable) I tried renaming "cfs2.exe" to "c2.exe" and the game tends to crash "less" but now there is a "pink outline" around the texts. With the latest radeon updates now the "cockpit 3d" mode is displayed in a tiny window (you have to manually enlarge it). I think it's another one of those unfixable games.

 "pink outline"
![Image](https://github.com/user-attachments/assets/d4f775bb-46c9-4bbc-879f-7aced8e26ec1)

![Image](https://github.com/user-attachments/assets/d2aab5c0-571d-43e1-b25c-ddbe1098f197)

**Comment by IllustriousProsperus** [comment]
Two crash dumps 
https://mega.nz/folder/TR9AxTTR#0LmQiP4gp8SqOOJQHixI4g

for the "cockpit"
2d cockpit
![Image](https://github.com/user-attachments/assets/35ced76c-faad-486a-b886-138baf4143e9)

3d cockpit
![Image](https://github.com/user-attachments/assets/07ea4343-d782-43d6-b12e-ce7fb3b3bc28)

the real problem is NOT enlarging the screen, but that sometimes it is full screen and sometimes not, it is a totally random thing as well as the crashes, I think the game is not capable of managing full screen and windowed mode...

very rarely does this happen in windowed mode

![Image](https://github.com/user-attachments/assets/aa67baef-5cea-47bb-b19e-725840fba53f)

I think there is nothing else that can be done

**Comment by narzoul** [comment]
The crash seems to be caused by a bug in the native ddraw runtime. It doesn't handle surface descriptor changes for DXTn textures correctly. I removed the dependency on that from DDrawCompat, I think that should fix it:
[ddraw.zip](https://github.com/user-attachments/files/19655974/ddraw.zip) ([diff.txt](https://github.com/user-attachments/files/19655975/diff.txt) compared to v0.6.0)

> With the latest radeon updates now the "cockpit 3d" mode is displayed in a tiny window (you have to manually enlarge it).

I can't reproduce this. You just change the view with the F4 key, right? It always makes it fullscreen for me, unless I first open a secondary camera view with F11, but that seems intentional. Also, how do you manually make it smaller or bigger? If it's some built in functionality in the game, then probably this isn't related to ddraw. I find it unlikely to be related anyhow, as the image is just too perfectly placed in a nice little frame in the top middle of the screen, so it has to be something the game requests from the API.

> very rarely does this happen in windowed mode

I found out that uxtheme.dll has some window hook that changes the window region (to apply rounded corners to the frame, I think), and for some reason it forgets to later reset it, but only when running with DDrawCompat. It might be some bug in Windows, probably triggered by some bad interworking with one of DDrawCompat's hooks, but I couldn't figure out which one yet. This will be a more long and boring investigation, I'll save it for later...

**Comment by Allen262** [comment]
**IllustriousProsperus** pic "DDrawCompat-v0.5.4 Invisible cockpit, map without the black rectangle". To me that has been around CFS2 since launch and still make aircraft and objects for CFS2 I can tell you that the 2d panel wasn't loaded and the black rectangle at the bottom of the screen isn't an error but done by the aircraft's panel.cfg text file to move the screen up so that the sight is put in the right spot to match the 2d panel .bmp. You can open any of the stock aircraft's panel.cfg and remove the render_3d_window=1 line. Once done you can click and hold on the panel to move it around and you can see the black rectangle at the bottom of the screen.

Never seen the "radar" be bug and rendered as back square. The main splash screen fully loading than reloading where only part of it load and the rest is black happens to me as well but sort of fixed with 0.6.0 as it dose fully load it right before loading to menu menu. All other menus do load fine overall and all other menus do load faster with 0.6.0. I've seen the problem with clouds once but can't get CFS2 to do it again and not sure what version of DDrawCompat I had at the time. Clouds could be just CFS2 jank.

I my self like may sim-outhouse have been running CFS2 with DgVoodoo2 in Windowed mode as DDrawCompat was just too crash prone for are liking and with Win11 Intel based APUs DgVoodoo2 is the only thing that has worked. 

My experience with 0.6.0 over the last 30-ish mins. All menu image do load faster than past versions of DDrawCompat. Haven't seen a crash yet. Cycling Windowed/Full screen can cause some sort of bug that I think it texturing everything with a water texture making every thing blue/teal. I'll keep DDrawCompat  0.6.0 installed while building and testing  the Edo XOSE-1 I'm working on and report back if the game crashes come back or anything else that could be from DDrawCompat.

![Image](https://github.com/user-attachments/assets/8973769d-3a0a-45f1-87d9-5035768666fd)

![Image](https://github.com/user-attachments/assets/04e3be53-7f4f-4d10-882d-1f3f4ffcc17c)

**Comment by narzoul** [comment]
The crash related to DXTn textures and the clipped window issues should be fixed in v0.7.0. You can also use GdiInterops=none to fix the startup banner (probably). I can't reproduce the rest of the issues reported here, so I don't know if those will ever be fixed. Need to know how to reproduce them first.

**Comment by narzoul** [comment]
v0.7.1 is out now. It might fix the blue tint issue too, but I'm not sure since I never had it. Are there still any remaining issues for this game?

**Comment by IllustriousProsperus** [comment]
Everything is working now 👍
