### ISSUE TITLE
TUC Command & Conquer and Red Alert black screen/freeze on first launch, but work fine afterwards

### ISSUE THREAD

**Issue by ReplicantKD637** [narzoul/DDrawCompat#387]
Hello, thanks for the wonderful wrapper.

I have the Ultimate Collection on Steam, which is bundled with your wrapper. No clue if the issue is on the game files or the wrapper, but I'll try to explain anyways.

So I boot my computer, try to launch Command & Conquer 95, resulting in a black screen and it freezes there, like it attempts to play the intro video but fails. I can close the process and then launch the game again, at which point the game works perfectly, and so does RA1.

This only happens with C&C95 and RA1.

I also have Dune 2000, which is not on Steam and it works perfectly with your wrapper.

I'm running Windows 11 Pro 24H2, 12gen Intel CPU and NVIDIA GPU.

**Comment by narzoul** [comment]
Same issue and same solution as here: #372

I've been working on a different approach to implement the CpuAffinty setting, by setting individual thread priorities instead of the whole process priority at once. My original intent was to allow certain threads to be excluded from the affinity restriction, such as DDrawCompat's own helper threads. But interestingly, with this approach, even if I restrict every single thread to a single core, it still avoids this strange bug on Windows 11 24H2. I don't know what is going on anymore.

You can either use CpuAffinity=all, or you can try the new CpuAffinity approach with this:
[ddraw.zip](https://github.com/user-attachments/files/17530155/ddraw.zip) ([diff.txt](https://github.com/user-attachments/files/17530156/diff.txt) compared to v0.5.4)

Note that the above patch already removes the CpuAffinity restriction for DDrawCompat's threads, driver threads (for DLLs under DriverStore), DirectSound and DirectInput. Although this doesn't seem necessary to fix this current issue, it might still improve performance overall when using single core affinity.

**Comment by narzoul** [comment]
Trying to debug the problem a little further, the only thing I could determine is that it must be related to audio somehow. After disabling all audio devices on my system (through Device Manager) and restarting my PC, I can no longer reproduce the freezes on startup. The game will complain about some DirectSound issue in a popup message, but after dismissing that, it will get to the main menu without sound fine. However, the game will instead freeze when exiting from the main menu, but that might be an altogether different bug in the game.

I'm not entirely sure if the issue is with DirectSound itself, or the way the game uses it, but every time I break into it with a debugger while it's frozen, the main thread is busy in some DirectSound method (usually some internal function called GetCurrentPosition). Using an older dsound.dll doesn't help, but the issue definitely wasn't present on 23H2.

Sometimes some dsound.dll threads are also in questionable state, like stuck in a LoadLibraryExA call trying to load avrt.dll, but bypassing that call doesn't solve the issue. Maybe someone with more experience with DirectSound could debug it further.

Anyway, this is rather off topic for DDrawCompat, and I'm quite content with the patch above for now.

**Comment by ReplicantKD637** [comment]
Thank you for the insight. Using Cpuaffinity=all worked wonders, I didn't notice anything going wrong so far (at least in C&C95).

**Comment by mrtnptrs** [comment]
> Same issue and same solution as here: [#372](https://github.com/narzoul/DDrawCompat/issues/372)
> 
> I've been working on a different approach to implement the CpuAffinty setting, by setting individual thread affinities instead of the whole process affinity at once. My original intent was to allow certain threads to be excluded from the affinity restriction, such as DDrawCompat's own helper threads. But interestingly, with this approach, even if I restrict every single thread to a single core, it still avoids this strange bug on Windows 11 24H2. I don't know what is going on anymore.
> 
> You can either use CpuAffinity=all, or you can try the new CpuAffinity approach with this: [ddraw.zip](https://github.com/user-attachments/files/17530155/ddraw.zip) ([diff.txt](https://github.com/user-attachments/files/17530156/diff.txt) compared to v0.5.4)
> 
> Note that the above patch already removes the CpuAffinity restriction for DDrawCompat's threads, driver threads (for DLLs under DriverStore), DirectSound and DirectInput. Although this doesn't seem necessary to fix this current issue, it might still improve performance overall when using single core affinity.

I can confirm that the adjusted patched DDrawCompat fixes the black screen boot on exit of Red Alert 2 on Windows 11 24H2.

**Comment by narzoul** [comment]
> I can confirm that the adjusted patched DDrawCompat fixes the black screen boot on exit of Red Alert 2 on Windows 11 24H2.

Thanks for testing it!

**Comment by narzoul** [comment]
I've added some more details in this NVIDIA forum post:
https://www.nvidia.com/en-us/geforce/forums/game-ready-drivers/13/561084/threads-getting-stuck-on-real-time-priority-on-win/

I've also created a small tool as a generic workaround for these issues, until it gets fixed in NVIDIA drivers (or Windows):
https://github.com/narzoul/NvUnboost

**Comment by narzoul** [comment]
With the help of a tool called [DTrace](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/dtrace), I was able to pinpoint the issue with much greater accuracy, and finally proved that the thread priorities are indeed messed up by the NVIDIA driver.

I created a DTrace script that traces the following kernel function calls:
- [KeQueryPriorityThread](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-kequeryprioritythread): used for querying the current dynamic priority of a thread
- [KeSetPriorityThread](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-kesetprioritythread): used for changing the current dynamic priority of a thread
- KiSetPriorityThread: undocumented, but seems to be used internally by KeSetPriorityThread to implement the actual priority change, as well as by other kernel functions that apply/revert dynamic priority boosts
- DxgkCddCreateDeviceBitmap: undocumented, but seems to be used e.g. for creating the window surface texture when a window is created or resized
- DdiCreateAllocation: undocumented (possibly related to [DxgkDdiCreateAllocation](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmddi/nc-d3dkmddi-dxgkddi_createallocation)), used during DxgkCddCreateDeviceBitmap to create the surface allocation

The script itself, as well as sample traces from Windows 11 23H2 and 24H2 with all of my GPUs (NVIDIA GeForce RTX 3060Ti, AMD Radeon RX 480, Intel UHD Graphics 770) are available here: [threadprio.zip](https://github.com/user-attachments/files/19931300/threadprio.zip)

I used Notepad.exe as a test subject, simply dragging its right side window border and continuously resizing it for a couple of seconds while recording the trace.

The script itself can be used as follows: `dtrace.exe -s threadprio.d 18164 16612`, where the first parameter (18164) is the Process ID (PID) to be traced, and the second parameter (16612) is the Thread ID (TID) of a thread within the process to be traced. Only those priority queries/changes are traced that target the specified thread, and only those allocations are traced that run in the context of the specified thread.

Optionally, the TID can be set to 0 to trace all threads in the process, but I didn't end up using this option for the sample traces for simplicity. Instead, I only traced the specific thread that reproducibly got stuck at 16+ priority when using the NVIDIA driver (or temporarily boosted to 15 priority on 23H2). I traced the same instance of Notepad.exe on all GPUs, and used NvUnboost in-between the tests to reset the stuck priorities. (NvUnboost was not running during the tests.)

For a quick overview, it's best to filter the traces with a regexp pattern like this: `KeQueryPriorityThread:return|KeSetPriorityThread:return| Start,| End,`

Let's start with `threadprio_nvidia_24h2.log`. Here's what happens while resizing the window, when the priority does not get stuck during a particular invocation of DxgkCddCreateDeviceBitmap:
```
  9   1946 0xff_0xffffffffffffffff:generic_event timestamp: 535007947139, DxgkCddCreateDeviceBitmap Start, caller: Notepad.exe (pid=18164, tid=16612, priority=10)
  9   1946 0xff_0xffffffffffffffff:generic_event timestamp: 535007988080, DdiCreateAllocation Start, caller: csrss.exe (pid=1516, tid=16612, priority=10)
  9   3498     KeQueryPriorityThread:return timestamp: 535008015111, priority: 10 (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=10)
  9   3498     KeQueryPriorityThread:return timestamp: 535008038404, priority: 10 (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=10)
  9   3498     KeQueryPriorityThread:return timestamp: 535008049407, priority: 10 (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=10)
  9   3500       KeSetPriorityThread:return timestamp: 535008066958, priority: 10 -> 12 => 12  (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=12)
  9   3498     KeQueryPriorityThread:return timestamp: 535008074961, priority: 12 (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=12)
  9   3500       KeSetPriorityThread:return timestamp: 535008097271, priority: 12 -> 16 => 16  (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=16)
  9   3500       KeSetPriorityThread:return timestamp: 535008114742, priority: 16 -> 16 => 16  (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=16)
  9   3500       KeSetPriorityThread:return timestamp: 535008126541, priority: 16 -> 12 => 12  (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=12)
  9   3500       KeSetPriorityThread:return timestamp: 535008136537, priority: 12 -> 10 => 10  (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=10)
  9   3498     KeQueryPriorityThread:return timestamp: 535008143344, priority: 10 (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=10)
  9   3498     KeQueryPriorityThread:return timestamp: 535008150322, priority: 10 (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=10)
  9   3498     KeQueryPriorityThread:return timestamp: 535008157112, priority: 10 (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=10)
  9   3500       KeSetPriorityThread:return timestamp: 535008165978, priority: 10 -> 12 => 12  (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=12)
  9   3498     KeQueryPriorityThread:return timestamp: 535008170864, priority: 12 (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=12)
  9   3500       KeSetPriorityThread:return timestamp: 535008179890, priority: 12 -> 16 => 16  (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=16)
  9   3500       KeSetPriorityThread:return timestamp: 535008190927, priority: 16 -> 16 => 16  (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=16)
  9   3500       KeSetPriorityThread:return timestamp: 535008200999, priority: 16 -> 12 => 12  (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=12)
  9   3500       KeSetPriorityThread:return timestamp: 535008210238, priority: 12 -> 10 => 10  (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=10)
  9   3498     KeQueryPriorityThread:return timestamp: 535008215716, priority: 10 (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=10)
  9   3498     KeQueryPriorityThread:return timestamp: 535008222238, priority: 10 (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=10)
  9   3498     KeQueryPriorityThread:return timestamp: 535008228771, priority: 10 (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=10)
  9   3500       KeSetPriorityThread:return timestamp: 535008237580, priority: 10 -> 12 => 12  (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=12)
  9   3498     KeQueryPriorityThread:return timestamp: 535008242279, priority: 12 (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=12)
  9   3500       KeSetPriorityThread:return timestamp: 535008251110, priority: 12 -> 16 => 16  (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=16)
  9   3500       KeSetPriorityThread:return timestamp: 535008262024, priority: 16 -> 16 => 16  (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=16)
  9   3500       KeSetPriorityThread:return timestamp: 535008272138, priority: 16 -> 12 => 12  (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=12)
  9   3500       KeSetPriorityThread:return timestamp: 535008281362, priority: 12 -> 10 => 10  (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=10)
  9   1946 0xff_0xffffffffffffffff:generic_event timestamp: 535008292339, DdiCreateAllocation End, caller: csrss.exe (pid=1516, tid=16612, priority=10)
  9   1946 0xff_0xffffffffffffffff:generic_event timestamp: 535009052054, DxgkCddCreateDeviceBitmap End, caller: Notepad.exe (pid=18164, tid=16612, priority=16)
```

The timestamps are supposed to be in nanoseconds (according to DTrace docs). `priority: 10 -> 12 => 12 (tid=16612)` means that the target thread of KeSetPriorityThread (with a Thread ID of 16612) was at priority 10 before calling KeSetPriorityThread, the target priority was set to 12, and finally, the number after the double arrow (=> 12) shows the new thread priority when KeSetPriorityThread returned. Sometimes, this final value may be different from the target value, e.g. if a dynamic priority boost is currently active, which can override the priority with a higher value.

KeSetPriorityThread is always invoked by the NVIDIA driver (nvlddmkm.sys), which can be confirmed by looking at the stack traces below each call (not shown above for brevity). It first boosts priority to 12, although as we'll see later, this can be skipped if the thread is already at 12+ priority. Then it boosts it to 16, then 16 again (redundantly), and finally reverts the first two boosts in reverse order by setting the priority back to what it was before each of those boosts (obtained by the preceding KeQueryPriorityThread calls I believe, although in theory it could also use the return value of KeSetPriorityThread). This boost cycle is repeated 3 times during each invocation of DdiCreateAllocation.

Here's an overview of what happens when things go wrong during a later resize:
```
  9   1946 0xff_0xffffffffffffffff:generic_event timestamp: 535033582415, DxgkCddCreateDeviceBitmap Start, caller: Notepad.exe (pid=18164, tid=16612, priority=10)
  9   1946 0xff_0xffffffffffffffff:generic_event timestamp: 535033610155, DdiCreateAllocation Start, caller: csrss.exe (pid=1516, tid=16612, priority=10)
  9   3498     KeQueryPriorityThread:return timestamp: 535033630891, priority: 10 (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=10)
  9   3498     KeQueryPriorityThread:return timestamp: 535033651845, priority: 10 (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=10)
  9   3498     KeQueryPriorityThread:return timestamp: 535033663275, priority: 10 (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=10)
  9   3500       KeSetPriorityThread:return timestamp: 535033676389, priority: 10 -> 12 => 12  (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=12)
  9   3498     KeQueryPriorityThread:return timestamp: 535033683180, priority: 12 (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=12)
  9   3500       KeSetPriorityThread:return timestamp: 535033694401, priority: 12 -> 16 => 16  (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=16)
  9   3500       KeSetPriorityThread:return timestamp: 535033709234, priority: 16 -> 16 => 16  (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=16)
  9   3500       KeSetPriorityThread:return timestamp: 535033722064, priority: 16 -> 12 => 12  (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=12)
  9   3500       KeSetPriorityThread:return timestamp: 535033733895, priority: 12 -> 10 => 10  (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=10)
  9   3498     KeQueryPriorityThread:return timestamp: 535033740919, priority: 10 (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=10)
  9   3502       KiSetPriorityThread:return timestamp: 535033865996, priority: 10 -> 16 => 16  (tid=16612), caller: dwm.exe (pid=1324, tid=2356, priority=16)
  9   3498     KeQueryPriorityThread:return timestamp: 535033881434, priority: 16 (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=16)
  9   3498     KeQueryPriorityThread:return timestamp: 535033897063, priority: 16 (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=16)
  9   3498     KeQueryPriorityThread:return timestamp: 535033903488, priority: 16 (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=16)
  9   3500       KeSetPriorityThread:return timestamp: 535033914886, priority: 16 -> 16 => 16  (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=16)
  9   3500       KeSetPriorityThread:return timestamp: 535033928431, priority: 16 -> 16 => 16  (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=16)
  9   3500       KeSetPriorityThread:return timestamp: 535033939070, priority: 16 -> 16 => 16  (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=16)
  9   3500       KeSetPriorityThread:return timestamp: 535033948773, priority: 16 -> 16 => 16  (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=16)
  9   3498     KeQueryPriorityThread:return timestamp: 535033955317, priority: 16 (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=16)
  9   3498     KeQueryPriorityThread:return timestamp: 535033962151, priority: 16 (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=16)
  9   3498     KeQueryPriorityThread:return timestamp: 535033968846, priority: 16 (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=16)
  9   3498     KeQueryPriorityThread:return timestamp: 535033973794, priority: 16 (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=16)
  9   3500       KeSetPriorityThread:return timestamp: 535033982656, priority: 16 -> 16 => 16  (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=16)
  9   3500       KeSetPriorityThread:return timestamp: 535033994130, priority: 16 -> 16 => 16  (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=16)
  9   3500       KeSetPriorityThread:return timestamp: 535034004112, priority: 16 -> 16 => 16  (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=16)
  9   3500       KeSetPriorityThread:return timestamp: 535034013292, priority: 16 -> 16 => 16  (tid=16612), caller: csrss.exe (pid=1516, tid=16612, priority=16)
  9   1946 0xff_0xffffffffffffffff:generic_event timestamp: 535034022738, DdiCreateAllocation End, caller: csrss.exe (pid=1516, tid=16612, priority=16)
  9   1946 0xff_0xffffffffffffffff:generic_event timestamp: 535034209643, DxgkCddCreateDeviceBitmap End, caller: Notepad.exe (pid=18164, tid=16612, priority=16)
```

Everything looks correct during the first boost cycle, and the priority returns from 12 to 10 at the end of it. But, before the second boost cycle begins, another process (dwm.exe) invokes KiSetPriorityThread and boosts the priority already to 16. Then, the NVIDIA driver queries a starting priority of 16, skips the initial boost to 12, and only executes the remaining 4 priority changes. But now, since the queries already returned a starting priority of 16, the last 2 reverts will simply revert to 16. And this is where the thread gets stuck running permanently at real time priority from here on. All further thread priority adjustments from the NVIDIA driver will always set the target priority to 16, because that's the new "initial" priority value before the boost cycle begins.

Let's look at why dwm.exe boosted the priority to 16 by checking the full stack trace of that call:
```
  9   3502       KiSetPriorityThread:return timestamp: 535033865996, priority: 10 -> 16 => 16  (tid=16612), caller: dwm.exe (pid=1324, tid=2356, priority=16)
              nt`KiBreakpointTrap+0x35b
              nt`KiSetPriorityThread+0x151
              nt`KiAbCpuBoostOwners+0x2d2
              nt`KiAbProcessThreadLocks+0xb48
              nt`KiAbProcessPreContextSwitch+0x15e
              nt`KiSwapThread+0x45
              nt`KiCommitThreadWait+0x483
              nt`KeWaitForSingleObject+0x7a4
              nt`ExpWaitForFastResource+0x92
              nt`ExpAcquireFastResourceExclusiveSlow+0x1e5
              nt`ExAcquireFastResourceExclusive+0x1bd
              win32kbase.sys`UserCritInternal::`anonymous namespace'::EnterCritInternal+0x4b
              win32kbase.sys`EnterCrit+0x50
              win32kfull.sys`xxxMoveEventAbsolute+0xdf
              win32kfull.sys`EditionCommitMousePosAndMove+0x7b
              win32kbase.sys`EditionCommitMousePosAndMove+0x7f
              win32kbase.sys`ApiSetEditionCommitMousePosAndMove+0x87
              win32kbase.sys`CMouseProcessor::CommitMousePosAndMoveCursor+0x1c8
              win32kbase.sys`CMouseProcessor::ProcessMouseInputData+0x2a3
              win32kbase.sys`CMouseProcessor::ProcessInput+0x656
              win32kbase.sys`CMouseSensor::ProcessInput+0x5e
              win32kbase.sys`CBaseInput::OnReadNotification+0xab
              win32kbase.sys`CBaseInput::OnDispatcherObjectSignaled+0x150
              win32kbase.sys`CBaseInput::_OnDispatcherObjectSignaled+0x12
              win32kbase.sys`IOCPDispatcher::HandleSensorDispatcherSignal+0xf6
              win32kbase.sys`IOCPDispatcher::Dispatch+0x28
              win32kbase.sys`UserKSTWait+0x159
              win32kbase.sys`NtKSTWait+0x16
              win32k.sys`NtKSTWait+0x25
              nt`KiSystemServiceCopyEnd+0x25
```

This seems to be one of the most common cases in general, but there are others, and not always from dwm.exe. Here, xxxMoveEventAbsolute tries to enter a critical section, but it's contested, presumably because our traced thread already entered the same critical section. This causes Windows to raise the priority of the critical section's current owner (our traced thread) to the same priority as the waiting thread, via the KiAbCpuBoostOwners function. I would guess that the intention is that another kernel thread should not be blocked waiting too long for a critical section, so the owner thread is boosted to help it get to a point where it can release the critical section and unblock the waiting thread.

Normally, these dynamic boosts are temporary and should be reverted shortly after the critical section is released. Here's an example of that from `threadprio_amd_24h2.log`, where such a dynamic boost persisted for the whole duration of DxgkCddCreateDeviceBitmap, but was reverted afterwards:
```
 15   3528       KiSetPriorityThread:return timestamp: 720140723647, priority: 14 -> 16 => 16  (tid=16612), caller: dwm.exe (pid=1324, tid=2356, priority=16)
 11   1946 0xff_0xffffffffffffffff:generic_event timestamp: 720140742928, DxgkCddCreateDeviceBitmap Start, caller: Notepad.exe (pid=18164, tid=16612, priority=16)
 11   1946 0xff_0xffffffffffffffff:generic_event timestamp: 720140769294, DdiCreateAllocation Start, caller: csrss.exe (pid=1516, tid=16612, priority=16)
 11   1946 0xff_0xffffffffffffffff:generic_event timestamp: 720140783833, DdiCreateAllocation End, caller: csrss.exe (pid=1516, tid=16612, priority=16)
  8   1946 0xff_0xffffffffffffffff:generic_event timestamp: 720140966268, DxgkCddCreateDeviceBitmap End, caller: Notepad.exe (pid=18164, tid=16612, priority=16)
  8   3528       KiSetPriorityThread:return timestamp: 720141139551, priority: 16 -> 10 => 10  (tid=16612), caller: Notepad.exe (pid=18164, tid=16612, priority=10)
```

The dynamic boost is reverted via KiAbThreadRemoveBoostsSlow, according to the stack trace of that last KiSetPriorityThread call:
```
  8   3528       KiSetPriorityThread:return timestamp: 720141139551, priority: 16 -> 10 => 10  (tid=16612), caller: Notepad.exe (pid=18164, tid=16612, priority=10)
              nt`KiBreakpointTrap+0x35b
              nt`KiSetPriorityThread+0x151
              nt`KiAbThreadRemoveBoostsSlow+0x26d
              nt`KiAbEntryFreeAndEnableInterrupts+0xe3
              nt`KeAbPostReleaseEx+0xae
              nt`ExpReleaseFastResourceExclusiveSlow+0x1f9
              nt`ExReleaseFastResource+0x6e5
              win32kbase.sys`ReleaseUserCriticalSection+0x2a0
              win32kfull.sys`LeaveEnterUserCritIfAcquired::LeaveEnterUserCritIfAcquired+0x40
              win32kfull.sys`SfnDWORD+0x12a
              win32kfull.sys`xxxHkCallHook+0x47a
              win32kfull.sys`xxxCallHook2+0x83f
              win32kfull.sys`xxxCallHook+0x11a
              win32kfull.sys`xxxSendTransformableMessageTimeout+0x3d2
              win32kfull.sys`xxxSendNCPaint+0xa4
              win32kfull.sys`xxxSimpleDoSyncPaint+0x2bb
              win32kfull.sys`xxxInternalDoSyncPaint+0x13
              win32kfull.sys`xxxInternalDoSyncPaint+0x204
              win32kfull.sys`xxxDoSyncPaint+0x55
              win32kfull.sys`xxxEndDeferWindowPosEx+0x593
              win32kfull.sys`xxxMoveSizeSetWindowPos+0x2b9
              win32kfull.sys`xxxDrawDragRectEx+0x4a7
              win32kfull.sys`xxxTM_MoveDragRect+0x3af
              win32kfull.sys`xxxMS_TrackMove+0x422
              win32kfull.sys`xxxMoveSize+0xe31
              win32kfull.sys`xxxSysCommand+0x30a
              win32kfull.sys`xxxRealDefWindowProc+0x13c1
              win32kfull.sys`xxxWrapRealDefWindowProc+0x73
              win32kfull.sys`NtUserfnDWORD+0x5f
              win32kfull.sys`NtUserMessageCall+0x18d
              win32k.sys`NtUserMessageCall+0x72
              nt`KiSystemServiceCopyEnd+0x25
```

However, when the NVIDIA driver requests the priority to be explicitly set to 16+, this presumably also prevents the system from reducing the priority back to where it was before the dynamic boost. Such boosts are documented not to apply to threads running at 16+ priority. It makes sense that the system would no longer reduce the priority even after the dynamic boost ends in this case, because that could undermine legitimate uses of KeSetPriorityThread that want to keep a driver-created thread's priority at a real-time level.

The two log files ending with `dwmrealtime` in the file name were executed with dwm.exe's process priority class raised to "Realtime" from the default "High" priority. This changes the priority of the contesting thread from 16 to 27. In practice, the only difference this causes is that KiAbCpuBoostOwners will now boost the traced thread's priority to 27 instead of 16, and the NVIDIA driver will set the target priority for its boosts to 27 instead of 16. This explains why sometimes threads are stuck at even higher than 16 priority.

The NVIDIA driver applies similar boosts also on 23H2. The main difference is that I've never observed 23H2 to apply a dynamic boost to 16+ priority. We can look for an example with xxxMoveEventAbsolute to see the difference, e.g. in `threadprio_nvidia_23h2_dwmrealtime.log`:
```
 10   3529       KiSetPriorityThread:return timestamp: 2215826731182, priority: 12 -> 15 => 15  (tid=6068), caller: dwm.exe (pid=1676, tid=2136, priority=27)
              nt`KiBreakpointTrap+0x34e
              nt`KiSetPriorityThread+0x807
              nt`KiSetPriorityBoost+0x39
              nt`KeSetPriorityBoost+0xbd
              nt`ExpApplyPriorityBoost+0x303
              nt`ExpApplyPrewaitBoost+0x6f
              nt`ExpAcquireResourceExclusiveLite+0x2fe
              nt`ExEnterCriticalRegionAndAcquireResourceExclusive+0xf1
              win32kbase.sys`PrivateAPI::`anonymous namespace'::EnterCritInternal+0x5a
              win32kbase.sys`EnterCrit+0x16
              win32kfull.sys`xxxMoveEventAbsolute+0xbb
              win32kfull.sys`EditionCommitMousePosAndMove+0x99
              win32kbase.sys`EditionCommitMousePosAndMove+0x84
              win32kbase.sys`ApiSetEditionCommitMousePosAndMove+0x125
              win32kbase.sys`CMouseProcessor::CommitMousePosAndMoveCursor+0x181
              win32kbase.sys`CMouseProcessor::ProcessMouseInputData+0xcd7cf
              win32kbase.sys`CMouseProcessor::ProcessInput+0x634
              win32kbase.sys`CMouseSensor::ProcessInput+0x5e
              win32kbase.sys`CBaseInput::OnReadNotification+0x16f
              win32kbase.sys`CBaseInput::OnDispatcherObjectSignaled+0xd8
              win32kbase.sys`CBaseInput::_OnDispatcherObjectSignaled+0x12
              win32kbase.sys`IOCPDispatcher::HandleSensorDispatcherSignal+0x7b
              win32kbase.sys`IOCPDispatcher::Dispatch+0x15
              win32kbase.sys`UserKSTWait+0x130
              win32kbase.sys`NtKSTWait+0x21
              win32k.sys`NtKSTWait+0x16
              nt`KiSystemServiceCopyEnd+0x25
```

As can be seen above, even though the calling thread in dwm.exe is running at 27 priority, the critical section's owner thread is only boosted to 15 priority, and it's applied via different functions. This behavior seems to have changed with 24H2, which is why the issue was not observed on 23H2, even though the driver was already applying similar boosts. Since the priority is never boosted to 16+ on 23H2, the dynamic boosts will still apply, and can reduce the priority later, even if the NVIDIA driver erroneously "reverts" the priority to a somewhat higher (dynamically boosted) priority.

I still believe this is primarily an NVIDIA driver issue, since according to the documentation of KeSetPriorityBoost, it's only intended to be used on driver-created threads. Yet the NVIDIA driver is clearly applying it to regular user threads that happen to create any windows. Even if NVIDIA is somehow exempt from this rule, it should take care not to apply such boosts when the thread is already running at real-time priority.

Neither the AMD, nor the Intel GPU drivers use KeSetPriorityBoost in similar ways, so likely these boosts are not necessary to begin with.

Some final notes:
When tracing all threads in Notepad.exe (I didn't include such a sample trace), it can be observed that DdiCreateAllocation can also be invoked by other threads, but these don't happen in the context of a DxgkCddCreateDeviceBitmap call. The NVIDIA driver applies similar boosts nevertheless, but I've never observed these to cause the priority to be stuck at a real-time value. One possible reason could be that the same contested critical section is not held in these other contexts, but this is only speculation.

**Comment by mrtnptrs** [comment]
@narzoul Was this possibly fixed in Windows 11 May 28, 2025—KB5058499 (OS Build 26100.4202) Preview Update? It mentions "[Graphics kernel] Fixed: An issue where some game titles become unresponsive after upgrading to 24H2." Which sounds like this issue honestly. Haven't had time to test this though.

**Comment by tinodin** [comment]
@narzoul The issue still exists in the latest version of Windows 25H2 and the latest NVIDIA driver v596.21, though only when changing the full screen resolution or when the game is running in FSE (Hardware: Legacy Flip). See https://github.com/Duckleeng/TweakCollection/issues/6#issue-4299052976
