### ISSUE TITLE
Links 2003 and antialiasing

### ISSUE THREAD

**Issue by BeepBoopWiggleWiggle** [narzoul/DDrawCompat#424]
Forcing AA in the nvidia panel causes many UI glitches (installing ddrawcompat disables AA).

From reading many forums it seems to be the concensus that it is impossible to get AA to function in Links.

I've tried different drivers, game patches and applications like dgvoodoo with no success.

Same results in W7, 10 and 11.

I've marked the issues in red:

![Image](https://github.com/user-attachments/assets/0264a212-b4ed-4841-9ab7-402a8fc09e21)

![Image](https://github.com/user-attachments/assets/4b221333-38a6-40c7-9e43-67622e34bae8)

**Comment by narzoul** [comment]
Forcing antialiasing from NVIDIA Control Panel does nothing for me, with or without DDrawCompat. I'm not even sure if it works with DirectDraw. Did you use it together with dgVoodoo or something? Or what settings did you use exactly to make it do anything at all?

Anyway, I couldn't check the full game because it just goes back to windowed mode and then shuts down as soon at it enters the main menu. There is no crash dump.

I tested the demo, but it needs CPU access to the ZBuffer, which is not supported by NVIDIA drivers when MSAA is enabled. It only works on Intel/AMD. This makes the player character flicker badly on NVIDIA with MSAA. It may be possible to work around it by rendering everything twice (with and without MSAA), but that's a good bit of effort to implement and it would likely have significant performance cost.

For the 2D line glitches, you can try the SpriteDetection=zconst setting, or maybe AlternatePixelCenter=on (but the latter screws up the text in the demo at least).

**Comment by BeepBoopWiggleWiggle** [comment]
Thanks for the suggestions, it didn't seem to have an effect unfortunately but I will try again.

The game is a purchased complete edition with the 1.07 patch that enables some nvidia support (like the golfers translucent shadow) and higher resolutions. I've tested with and without these patches unsuccessfully.

Regarding dgV etc. I only tested them independently.

**Comment by narzoul** [comment]
Antialiasing should now work in v0.7.1 on all GPUs.

**Comment by BeepBoopWiggleWiggle** [comment]
Thank you for your continued work on this issue.
I've tested this release and the behaviour in Links has improved but not resolved.
Enabling AA in the nvidia panel for Links now produces no UI errors 👍, but AA appears to not be applied in the rendering. 
The golfers opaque shadow is still corrupt/invisible as before.
Attached is a screenshot showing these issues with 8x AA selected.

![Image](https://github.com/user-attachments/assets/5117ec5b-fab8-4da6-8fc4-ca6916a73d0e)

**Comment by narzoul** [comment]
You're supposed to enable Antialiasing in DDrawCompat, not in the NVIDIA Control Panel. In fact, you'd probably better turn it off there, I don't know what it can interfere with.

**Comment by BeepBoopWiggleWiggle** [comment]
Thank you, I've also tried that but the results are the same.

**Comment by narzoul** [comment]
Well, I don't know then. I can only test the demo because the full game doesn't work for me, and Antialiasing works in the demo on NVIDIA.

**Comment by BeepBoopWiggleWiggle** [comment]
Okay, I'll grab the demo and try that, cheers.

**Comment by BeepBoopWiggleWiggle** [comment]
So I've tested the identical settings in the demo and I'm getting the same issues.
I guess it comes down to my particular hardware/drivers.
Thank you for your help though.

**Comment by SonarRulls** [comment]
Have you tried using Reshade? For example I used ResolutionScale to Display (1) through DDrawCompat settings
With Sacred Gold and combining with resolution 1366x768 (this way UI won't shrink with high resolution)  and by using cheap Antialiasing through Reshade, since MSSA adds vertical white lines in the game in some cases.

**Comment by SonarRulls** [comment]
Also you may want check mobygames website under their specs section for your specific games, they offer more info than pcgamingwiki at times.

**Comment by narzoul** [comment]
> So I've tested the identical settings in the demo and I'm getting the same issues. I guess it comes down to my particular hardware/drivers. Thank you for your help though.

Well, since you have identical problems with the demo, we can use that for further debugging. Can you please enable LogLevel=debug with v0.7.1 and upload the debug logs? Just get to the part where the golfer is rendered and press ctrl+alt+end to terminate the process. Compress and upload the logs. Thanks!

> Have you tried using Reshade? For example I used ResolutionScale to Display (1) through DDrawCompat settings With Sacred Gold and combining with resolution 1366x768 (this way UI won't shrink with high resolution) and by using cheap Antialiasing through Reshade, since MSSA adds vertical white lines in the game in some cases.

Reshade shouldn't be necessary for Sacred. These settings work well for me to clean up any artifacts caused by MSAA and resolution scaling:
```
SpriteAltPixelCenter = custom(-1)
SpriteDetection = zmax(0)
SpriteTexCoord = clamp
```

**Comment by BeepBoopWiggleWiggle** [comment]
Before I proceed further, I cannot find the .ini files and in the log it reports this:

12:48:08.912 Process path: C:\Program Files (x86)\Microsoft Games\Links 2003 Demo\LINKSMMIII.EXE
12:48:08.912 Loading DDrawCompat dynamically from C:\Program Files (x86)\Microsoft Games\Links 2003 Demo\DDRAW.dll
12:48:08.912 DDrawCompat version: v0.7.1
12:48:08.912 Windows version: 10.0.26200
12:48:08.912 Environment variable __COMPAT_LAYER = "RunAsAdmin ElevateCreateProcess"
12:48:08.912 Loading global config file: C:\ProgramData\DDrawCompat\DDrawCompat.ini
12:48:08.912   File not found, skipping
12:48:08.912 Loading user config file: C:\Users\User\AppData\Local\DDrawCompat\DDrawCompat.ini
12:48:08.912   File not found, skipping
12:48:08.912 Loading directory config file: C:\Program Files (x86)\Microsoft Games\Links 2003 Demo\DDrawCompat.ini
12:48:08.912   File not found, skipping
12:48:08.912 Loading process config file: C:\Program Files (x86)\Microsoft Games\Links 2003 Demo\DDrawCompat-LINKSMMIII.ini
12:48:08.912   File not found, skipping
12:48:08.912 Loading overlay config file: C:\Program Files (x86)\Microsoft Games\Links 2003 Demo\DDrawCompatOverlay-LINKSMMIII.ini
12:48:08.912   File not found, skipping

**Comment by BEENNath58** [comment]
Uh it seems you haven't yet enabled AA in DDrawCompat, hence you don't have the ini in the first place???

**Comment by BeepBoopWiggleWiggle** [comment]
Okay I think I've done what you've asked...

[DDrawCompat-LinksMMIII.zip](https://github.com/user-attachments/files/24874682/DDrawCompat-LinksMMIII.zip)

**Comment by narzoul** [comment]
So does MSAA work now that you set the config file correctly?

I also just realized, when I told you to turn it off in the NVIDIA Control Panel, I didn't realize there is a literal off setting, which does kill antialiasing even on my system. It should be set to application-controlled instead. Sorry about the confusion.

**Comment by BeepBoopWiggleWiggle** [comment]
MSAA is working thank you, 
I am still getting the UI issue of it leaving white vertical lines onscreen after closing a menu.
The golfers shadow is invisible (this happens if your .dll is in the game folder, regardless of its AA setting).
If the top down camera window is used, its border still has black and white dashes.
I've included a new screenshot, definite improvment over the default nvidia AA (which Ive set to default app controlled settings thanks).
I don't know if this is related to the above, but Ive had to set the exe properties to 'override high DPI scaling', if I dont the greens analyser 3D window just draws off the screen like a continuous mouse movement - only happens if AA selected.

![Image](https://github.com/user-attachments/assets/dc99e9ce-ef7c-464a-99ba-c2f313d5f1b4)

**Comment by narzoul** [comment]
This patch should fix the translucent shadows and enable it on all GPUs:
[ddraw.zip](https://github.com/user-attachments/files/24948663/ddraw.zip) ([diff.txt](https://github.com/user-attachments/files/24948664/diff.txt) compared to v0.7.1)

The `SpriteDetection=zconst` setting fixes the MSAA line bugs for me on NVIDIA and AMD, but not on Intel for some reason.

> I don't know if this is related to the above, but Ive had to set the exe properties to 'override high DPI scaling', if I dont the greens analyser 3D window just draws off the screen like a continuous mouse movement - only happens if AA selected.

I don't really understand this and I can't reproduce it. I saw from your logs that you have 125% DPI scaling in Windows so I tried with the same, but it doesn't cause any such problems for me. The Green analyzer opens centered on the screen.
If I override DPI scaling to "System", then I can't move the mouse to the bottom of the screen so I can't even select the Green analyzer from the menu. If I override it to "Application", then it works fine, but it's the same as the default setting of DDrawCompat, which works the same way.
Moreover, I can't fathom what any of this would have to do with antialiasing, which should be absolutely unrelated to DPI scaling or window positions...

Note: I'm still using the demo for testing, which has a fixed resolution of 1280x1024, and I can't change it in the in-game settings (it's greyed out). I saw that your game runs at 2560x1440. It doesn't even try to set any resolution so it just inherits the desktop's resolution. I don't know how you achieved that.

**Comment by BeepBoopWiggleWiggle** [comment]
The patch works thank you, shadow is back.
I forgot to mention I run the game windowed at 1280x1024.
Regarding the issue with the Green analyzer, your new patch seems to have fixed it as it now behaves correctly, regardless of high DPI settings and using AA. 
Also, what used to happen with that setting is the scale of the menu fonts was too large for the window, that is now fixed.
I've applied your sprite detection setting and that's eliminated the white line issue :)
Another thing that's fixed is anisotropic filtering, that would cause artifacts on the title menu and sometimes rendering issues around the ball.
I've also tested in full screen, in a variety of resolutions and all works great.
Amazing effort, thank you so much!!!!!!

**Comment by dwg1957** [comment]
I have done a fair amount of testing of this version on a Notebook running Windows 11 with embedded Intel Iris Xe Graphics, Links full screen at a resolution 1920 x1080. I last tested version 0.6.0 which had significant issues.

I would like to thank you for your efforts.

Previous I was using dgVoodoo to make Links run at all on the configuration. But that still has some problems with some courses hanging and various other problems with No golfer translucent shadows and some camera views corrupted. DgVoodoo has also regressed in the more recent releases, we have been stuck using an older version.

With this latest version Links is running well, the course that were hanging before run as they should (I had identified 11 problem courses). 

Translucent shadows work.

All camera views are working, even when there are 7 views concurrently on the desktop.

I did have to disable Sprite Detection with the Intel graphics to correct an issue with a camera view, one image looked scratchy. This was the top camera view of the hole. So far no other problems encountered.

I believe this makes for an excellent solution for the Links community. It is more complete and more robust than what we had.

Again, thank you.

**Comment by BeepBoopWiggleWiggle** [comment]
Hello Narzoul, again brilliant work thank you.

Infrequently Links is crashing and reporting this error:
"FAILED (0x887601ae - DDERR_SURFACEBUSY) - Lock(0xacbe100,NOSYSLOCK READONLY WAIT )"
I haven't been able to reproduce this error, it seems random, I have not made any changes to the games parameters.

Would appreciate your input please?

**Comment by dwg1957** [comment]
Is it any specific course it seems to occur with?

Am happy to try it here if so.

**Comment by BeepBoopWiggleWiggle** [comment]
No course in particular, its random, thanks.

**Comment by narzoul** [comment]
Sounds like a bug in the game. It's trying to lock a surface that it has already locked before and hasn't unlocked yet. It would need to be patched in the game itself.
Doesn't it happen without DDrawCompat too? I don't think there is anything in DDrawCompat that could cause this problem.

**Comment by BeepBoopWiggleWiggle** [comment]
I've been playing the game for some years, and I vaguely recall it happening previously.
The benefits of DDrawCompat far outweigh the issue that's for sure.
I just thought I'd get you opinion on it, thanks again.

**Comment by dwg1957** [comment]
I wonder if you would indulge me with a question.

The version of Links we are using allows you to set discrete resolution for the game, up to 1920 x 1200, we use an integer in a specific registry key to set it. Links allows you to run in a Window or full screen. There are an increasing number of higher resolution monitors on the market, that are obviously of higher resolution than Links has settings for.

For those that want to run Links full screen are there any settings in DDrawcompat that would facilitate it e.g, allow Links to be say set to 1920 x 1080 itself yet output full screen to a 3820 x 2160 display. I've looked at the options, but none are standing out for me.

Thanks

**Comment by narzoul** [comment]
> For those that want to run Links full screen are there any settings in DDrawcompat that would facilitate it e.g, allow Links to be say set to 1920 x 1080 itself yet output full screen to a 3820 x 2160 display. I've looked at the options, but none are standing out for me.

This is already how it works by default. The output resolution of DDrawCompat is controlled by the DisplayResolution setting, which is by default equal to your desktop resolution (e.g. 3840x2160). If the game uses a lower internal resolution, it will be upscaled to the specified DisplayResolution, using the filter set by DisplayFilter.

**Comment by dwg1957** [comment]
Thank you for the information that should prove very useful. I've read the settings you have pointed out and see what you mean.

I'm thinking that in Links it would be best to choose a resolution that has the same aspect ratio as the screen, certainly the best settings in Links is something to ponder on.

You have been very helpful, I appreciate it.

**Comment by narzoul** [comment]
If the aspect ratios are not the same, you can choose to stretch the output more in one direction (generally horizontally) to fill the screen, or keep the aspect ratio and have black bars on the sides. Default is to keep aspect ratio. It can be controlled with the DisplayAspectRatio setting.

But yes, if the game supports the same aspect ratio as your native resolution, then that's usually the best option.

**Comment by dwg1957** [comment]
Thanks, I think I am starting to get a good handle on settings to at least try when using Links.

Higher resolution monitors have proven to be difficult hardware to use with Links at times.

**Comment by john-iv** [comment]
Should this wrapper work w/ discrete AMD cards (5600XT)? I dropped it in to my system and on launch I get a black rectangle for the UI window that has to be killed via taskmanagr.  Usually I play LS2k3 successfully w/ the Radeon software via overriding app AA and forcing anisotropic filtering.  Here's my log.  Normally I launch windowed (which start w/ no AA), then alt-enter to go fullscreen which activates the anti-aliasing w/ the newest AMD drivers, then alt-enter again to go back to windowed which now inherits and keeps the AA setting.  Was hoping this wrapper would allow bypassing that extra step.

[DDrawCompat-LinksMMIII.log](https://github.com/user-attachments/files/25088977/DDrawCompat-LinksMMIII.log)

**Comment by narzoul** [comment]
Please check this patch: https://github.com/narzoul/DDrawCompat/issues/553#issuecomment-3829048659
Or alternatively v0.7.0, since v0.7.1 has a bug that's apparently more likely to affect RDNA GPUs.

**Comment by john-iv** [comment]
Hi, tried the patch and the difference is w/ the patch I now get a titlebar and windows controls in the upper right of the previously black empty rectangle, so progress? Laugh. I'll try straight 7.0 next.  Here's the log:

[DDrawCompat-LinksMMIII.log](https://github.com/user-attachments/files/25089716/DDrawCompat-LinksMMIII.log)

**Comment by john-iv** [comment]
Same issue as the patch when trying to use 7.0, get the titlebar and controls but empty UI. 

[DDrawCompat-LinksMMIII.log](https://github.com/user-attachments/files/25089788/DDrawCompat-LinksMMIII.log)

**Comment by narzoul** [comment]
There are no errors in your logs, but the second one got further, so maybe let's start with that one. Please use v0.7.0 with LogLevel=debug in DDrawCompat.ini and share your logs again.

**Comment by john-iv** [comment]
> There are no errors in your logs, but the second one got further, so maybe let's start with that one. Please use v0.7.0 with LogLevel=debug in DDrawCompat.ini and share your logs again.

Here you go w/ debug on.

[DDrawCompat-LinksMMIII.log](https://github.com/user-attachments/files/25111511/DDrawCompat-LinksMMIII.log)

**Comment by narzoul** [comment]
That's odd, it looks like your driver is crashing in a simple surface copy from system memory to video memory. Maybe it can't handle the large pitch due to your multiple monitors?

Can you please try the same (v0.7.0 + LogLevel=debug) with your second monitor removed from the desktop?

If it doesn't work, then try again with `GdiInterops=none` in DDrawCompat.ini, with both monitors enabled.

Please share logs again for the cases above that still don't work.

**Comment by john-iv** [comment]
Hello, some good news to report. With 7.0:
1. Disconnect secondary monitor, debug on in compat.ini, game works and plays. debug log produced 700MB logfile 30MB zipped..
2. Reconnect secondary monitor, add gdiinterops=none, game works and plays. debug log produced 700MB logfile again 30MB zipped.
3. Reconnect secondary monitor, add gdiinterops=none, disable debug, game plays and log is normal size (attached).

[DDrawCompat-LinksMMIII.log](https://github.com/user-attachments/files/25134588/DDrawCompat-LinksMMIII.log)

Here are the two large debug logs zipped on my onedrive: https://1drv.ms/f/c/eeb899b77dc95a92/IgBLWkLXTx9yRKbSrPgGxahyAejDHfuZil49TD-9Yl-GNXY?e=vnNCCi

The only two alterations on the AMD side I usually make in the AMD software is turning on AA 8EQ Supersampling and 16X Anisotropic filtering.  How do I accomplish that in your ddrawcompat.ini?  [Update: Found the overlay after RTFMing and set them there]. Thanks for your help -

PS: Went up to 7.1 and it works too, fyi.

PS2: I noticed on my system w/ a 4K 144DPI monitor I had to enable the Windows 11 DPI compat. toggle on the .exe to get it to the scaled size I was used to w/ the AMD software which may have done that itself.  The highest we can take Links2K3 is 1920x1200 w/ patch 1.07.  I read above that in the thread that your wrapper should be increasing the size w/out the need for the DPI 'cheat' from Windows 11.

**Comment by narzoul** [comment]
> PS2: I noticed on my system w/ a 4K 144DPI monitor I had to enable the Windows 11 DPI compat. toggle on the .exe to get it to the scaled size I was used to w/ the AMD software which may have done that itself.

I guess you could achieve the same by setting DpiAwareness=unaware in DDrawCompat.ini. This is needed to apply DPI scaling for windowed mode. But it tends to introduce issues in fullscreen mode, so it's not the default setting.

Would you be willing to test a few more patch attempts? I'd prefer not to tell every RDNA user to set GdiInterops=none (it might break some games anyway) or to disable their secondary monitors, so it would be good to find a proper fix for this.

I also noticed some remaining issues in your new logs. Mipmap creation in system memory fails when DDrawCompat does it directly through pfnCreateResource2, but it succeeds when the request comes from the ddraw runtime. My best guess it that the driver rejects it because I set the hResource parameter to null. I think this might be easily fixable, so I'll look into this too. I wonder if it would coincidentally also solve that strange driver crash you have without GdiInterops=none.

**Comment by john-iv** [comment]
Certainly, I'd be glad to help.  I'm retired, in the PST timezone (Seattle-ish) for speed of reply/communication.

**Comment by narzoul** [comment]
Here's the first test version: [ddraw.zip](https://github.com/user-attachments/files/25138167/ddraw.zip) ([diff.txt](https://github.com/user-attachments/files/25138172/diff.txt) compared to v0.7.1)

It's supposed to just fix the mipmap issue, but maybe if we're lucky it also fixes the black screen issue (unlikely).
So please try it without the GdiInterops=none setting, but with LogLevel=debug.

If it manages to fix the black screen, then start a game and you can just exit as soon as it's finished loading/rendering the 3D part. Then share the logs again.

If it doesn't fix the black screen, then repeat the same with GdiInterops=none and upload the logs from that run instead.

Thanks!

**Comment by john-iv** [comment]
With new patch:
1. Get black screen after removing gdi setting.
2. Here's the non-debug log with gdi setting back in.
3. Note also that when AA is on, in the splash screen you'll get those thin black vertical lines, but they seem to go away while in game after the scene renders.  They'll come back if you open a dialogue on screen and dismiss it.  That's been reported further up the thread. I just mention this in passing as the lines on the landing page don't really bother me.

<img width="1926" height="1229" alt="Image" src="https://github.com/user-attachments/assets/fb70cab6-cabc-4f39-86f3-965fc4d1e13c" />

[DDrawCompat-LinksMMIII.log](https://github.com/user-attachments/files/25138344/DDrawCompat-LinksMMIII.log)

**Comment by narzoul** [comment]
> Get black screen after removing gdi setting.

Unfortunate, but thanks for testing it! I'll try something else later.

> Here's the non-debug log with gdi setting back in.

Uhh, sorry if I was unclear about this, but I actually need debug logs for this too. So please repeat it with both GdiInterops=none and LogLevel=debug. Thanks!

> Note also that when AA is on, in the splash screen you'll get those thin black vertical lines, but they seem to go away while in game after the scene renders. They'll come back if you open a dialogue on screen and dismiss it. That's been reported further up the thread. I just mention this in passing as the lines on the landing page don't really bother me.

The `SpriteDetection=zconst` setting is supposed to fix that, please try it. No need for any logs on this one. If it doesn't help, maybe try also changing your driver AA settings to "Use application settings". I'm not sure if that's necessary or not.

**Comment by john-iv** [comment]
Here you are. 

[DDrawCompat-LinksMMIIIdebugnogdi.log](https://github.com/user-attachments/files/25138731/DDrawCompat-LinksMMIIIdebugnogdi.log)
[DDrawCompat-LinksMMIIIdebuggdion.zip](https://github.com/user-attachments/files/25138730/DDrawCompat-LinksMMIIIdebuggdion.zip)

Also looks like spritedetection=zconst took care of the lines, thanks.

**Comment by dwg1957** [comment]
The image with the vertical black lines attracted my interest, I see that on a machine with an Intel iGPU.

On this machine spritedetection=zconst causes issues with the Top Camera view where I get criss cross patterns of short black lines.

Disabling this setting fixes the patterns but causes the borders of the camera view Windows to be corrupted.

After some experimenting, I found that spritedetection=point resolves the patterns in the top camera view, the window border around the embedded windows draw correctly and I no longer appear to get the black vertical lines anywhere, I was generally seeing 2 of them in roughly the same position as the screenshot above.

I did try some Zmax settings instead but could not detect any difference.

**Comment by BeepBoopWiggleWiggle** [comment]
Sometimes I'm finding DDrawCompat's anisotropic filtering is causing part of the translucent golfer's shadow and/or the tracer following the ball's trajectory to be left on screen.
Forcing AF via the GPU produces the same issue (no DDrawCompat installed).
Point, bilinear and trilinear fixes this in both approaches.
Do you have any suggestions how I could configure DDrawCompat to apply AF without these artifacts?
Thanks again.

**Comment by narzoul** [comment]
> Here you are.
> 
> [DDrawCompat-LinksMMIIIdebugnogdi.log](https://github.com/user-attachments/files/25138731/DDrawCompat-LinksMMIIIdebugnogdi.log) [DDrawCompat-LinksMMIIIdebuggdion.zip](https://github.com/user-attachments/files/25138730/DDrawCompat-LinksMMIIIdebuggdion.zip)
> 
> Also looks like spritedetection=zconst took care of the lines, thanks.

Here's another experiment: [ddraw.zip](https://github.com/user-attachments/files/25154583/ddraw.zip) ([diff.txt](https://github.com/user-attachments/files/25154584/diff.txt) compared to v0.7.1)

Please enable LogLevel=debug but don't use GdiInterops=none. If you don't get a black screen, then also enter a game and wait for the 3D scene to load before quitting. Then share the logs again. Thanks!

> Do you have any suggestions how I could configure DDrawCompat to apply AF without these artifacts?

Not really. I assume these aren't sprites and all of the settings to deal with such problems have to do with sprites (or resolution scaling, which you didn't mention using). It might not be solvable. Anyway, I don't have time to look into this now, as there are several more important issues to be fixed first. Maybe I'll look into this later.

**Comment by john-iv** [comment]
> Please enable LogLevel=debug but don't use GdiInterops=none. If you don't get a black screen, then also enter a game and wait for the 3D scene to load before quitting. Then share the logs again. Thanks!

This patch worked, I was able to remove GDI and it ran successfully. Here is the log, thanks!

[DDrawCompat-LinksMMIII.zip](https://github.com/user-attachments/files/25156518/DDrawCompat-LinksMMIII.zip)

PS : One more question.  When using your wrapper in this fashion everything on the inside is looking good for me, but is there a way to return to the Windows 11 chrome for the titlebar and control buttons? Currently when using the wrapper it is defaulting back to the Vista era or beyond. :)  Thanks -

<img width="3078" height="1796" alt="Image" src="https://github.com/user-attachments/assets/a57531c2-9f90-4c1e-aa91-2941dfcbb0df" />

**Comment by dwg1957** [comment]
A question, 

Does the ddraw file provide to john-iv include the Links Translucent golfer shadow fix? i.e are the fixes cumulative.

I'm just wondering if we should be using this version for all Links installations, or do we need to maintain separate kits.

Thanks

**Comment by narzoul** [comment]
> A question,
> 
> Does the ddraw file provide to john-iv include the Links Translucent golfer shadow fix? i.e are the fixes cumulative.
> 
> I'm just wondering if we should be using this version for all Links installations, or do we need to maintain separate kits.
> 
> Thanks

It doesn't include the shadow fix, but you don't need a combined patch. Just use the shadow patch with GdiInterops=none.

> PS : One more question. When using your wrapper in this fashion everything on the inside is looking good for me, but is there a way to return to the Windows 11 chrome for the titlebar and control buttons? Currently when using the wrapper it is defaulting back to the Vista era or beyond. :) Thanks -

GdiInterops=none should fix that too. Specifically it's the "themes" part of the setting that changes the window theme to the old style.

**Comment by john-iv** [comment]
> > PS : One more question. When using your wrapper in this fashion everything on the inside is looking good for me, but is there a way to return to the Windows 11 chrome for the titlebar and control buttons? Currently when using the wrapper it is defaulting back to the Vista era or beyond. :) Thanks -
> 
> GdiInterops=none should fix that too. Specifically, it's the "themes" part of the setting that changes the window theme to the old style.

Yep, that worked, thanks again.

**Comment by narzoul** [comment]
> Sometimes I'm finding DDrawCompat's anisotropic filtering is causing part of the translucent golfer's shadow and/or the tracer following the ball's trajectory to be left on screen. Forcing AF via the GPU produces the same issue (no DDrawCompat installed). Point, bilinear and trilinear fixes this in both approaches. Do you have any suggestions how I could configure DDrawCompat to apply AF without these artifacts? Thanks again.

I can't reproduce this. Are you only using anisotropic filtering or also some other overrides? Can you record a video of what happens?

**Comment by BeepBoopWiggleWiggle** [comment]
Thanks for the reply, it was easier for me to grab screenshots as it is a random event.

One grab shows the shadow artifact on the ground after the swing. 

The other shows the ball with comet trail artifacts - if trajectory is high enough the ball leaves the game window and as the ball's comet trail is drawn it sometimes leaves part of itself behind, always at the top of screen (purple arrows). The green arrow shows the ball and trail re-entering frame, drawing correctly.
Usually I'll see a comet trail fragment stay on screen briefly and it looks like the screen redraws and its cleared as the ball re-enters frame which I guess is correct behaviour.

I've tried windowed/fullscreen, different resolutions and desktop scaling on/off, same results.

I've realised I can reproduce the comet trail issue with a default install of the game so I guess that problem is either a driver/game issue.

![Image](https://github.com/user-attachments/assets/00e0f66d-def4-4690-95df-6dc5021d11e1)

![Image](https://github.com/user-attachments/assets/2224ee88-7644-46e2-b6ad-16f19488669d)

**Comment by dwg1957** [comment]
I'm using comet tails on my systems. I am not seeing a problem when using Links on a notebook with an Intel GPU with DDrawCompat, nor on my desktop which just has Nvidia with no wrapper.

**Comment by narzoul** [comment]
I could reproduce the comet trail issue a few times, but it happens without any graphical enhancements as you said, so I also think it's just a bug on the game side.

I can not reproduce the shadow artifact on the ground and I don't even understand what is supposed to leave it. The ball doesn't seem to have a shadow in my game. Maybe it needs specific game settings or a specific map, I don't know, I gave up on it for now, I'm not really good at this game. If reproducing it even once can take hours and I'd have to repeat it dozens of times to experiment with various fix attempts, I would never do anything else this year.

**Comment by BeepBoopWiggleWiggle** [comment]
The shadow left on the ground is from the club's head as its swung past the ground.
Thank you for looking into this and I agree its not worth spending any more time on it, your efforts on the game have been greatly appreciated.

**Comment by dwg1957** [comment]
Sorry to trouble you again.

I wonder if you might have some ideas about the brown object in the background.

I do not see it on machines that do not have DDrawCompat on them (Nvidia HBA)

If I replace DDrawCompat with dgVoodoo I am not seeing it either.

![Image](https://github.com/user-attachments/assets/80898158-3299-462b-8ac5-177f418cb2fe)

**Comment by narzoul** [comment]
Can you send a save game that immediately shows this problem upon loading? I tried playing this course for a while but didn't see any similar issues.

**Comment by dwg1957** [comment]
I cannot guarantee it will happen in any round. I will see if I can get it into a needed position in practice mode save it and send that.

I have gone over Hole 3 in practice mode moving the ball around a lot and it turns out it is very positional dependent. This is the only way I have been able to reliable get the ball in a position where it occurs but as I said it requires me positioning the ball by hand - which you can do in practice mode.

It seems to occur mostly with the ball near the start of the left hand or right hand side of the fairway, but you move the ball slightly and it changes shape or disappears.

I may have found a workaround, but am not 100% certain. I have set VertexFixup = cpu in DDrawCompat's configuration and have not been able to reproduce the artefact since.

**Comment by dwg1957** [comment]
Looks like I had saved one of my practice rounds when I saw the problem. I had to zip the file as this system does not like .sav files

[nsw.zip](https://github.com/user-attachments/files/26010712/nsw.zip)

**Comment by narzoul** [comment]
Thanks! Unfortunately I can't reproduce the issue on any of my 3 GPUs even with your save game. I see this:
![Image](https://github.com/user-attachments/assets/7697a86e-a3d9-49e6-83f7-4fe092ebff2a)

Maybe it depends also on some in-game settings or it's a hardware/driver specific issue. Can you share your DDrawCompat log file?

**Comment by dwg1957** [comment]
Sure log attached.

In game I had set the VertexFixup to GPU and went to a number of problem places on the hole, I have identified 6 so far.

As far as I am aware all the folks that have seen this are using an Intel GPU.

[DDrawCompat-LINKSMMIII.log](https://github.com/user-attachments/files/26019206/DDrawCompat-LINKSMMIII.log)

**Comment by narzoul** [comment]
I copied your settings (except that I kept VertexFixup=gpu) but still can't repro the issue, even on an Intel UHD 770. It's a 12th gen GPU while yours I think is an 11th gen, so yours uses the older Intel driver architecture (before trinity). Most likely I won't be able to reproduce the issue as it would require an older Intel GPU, which I don't have. So I don't think I'll be able to fix it.
But if VertexFixup=cpu fixes it, then I'd recommend just using that.

**Comment by dwg1957** [comment]
Yes it is a 11th Gen i5 CPU with Intel Iris XE graphics.

I do have a Gen 13 system but it has an Nvidia HBA in it and no problems.

I am search for more problems on that hole when using the VertexFixup=GPU setting and saving them. I will go back and reload each with the setting changed to cpu and see if the problem still exists.

I will see if the others can tell me what CPU they have.

**Comment by BeepBoopWiggleWiggle** [comment]
Hello Narzoul, I've just replaced my laptop with a Lenovo P51 which uses hybrid graphics and I've run into a problem with Links 2003. Despite my best efforts I have not been able to make the OS 'see' Links booting and switch to the NVIDIA GPU like it does for other 3D programs in hybrid graphics mode.
I've tried power profiles, bios settings, drivers, reg edits and cfg. files. I've tried various wrappers and they all seem to run slowly suggesting it's still running on the Intel graphics. Without a wrapper it does run on the Intel smoothly, but there is a graphics issue with the sky which is something to do with the Intel not fully implementing DirectX (and the green-analyser scrolling issue returns).
If I boot using discrete mode Links does see the NVIDIA GPU which would normally be ok... except this particular model of ThinkPad does not wake the display when resuming from sleep/lock screen timeout (an issue they never fixed and a rabbit hole I spent some time in), requiring a reboot. Hybrid mode does not have this issue.
Now that's out the way my question/request is, is there something you can do with DDrawCompat to make the OS assign the NVIDIA card to Links in hybrid mode like it does with other 3D apps?
Thanks.

**Comment by narzoul** [comment]
I don't think so. As far as I can tell, MS didn't implement hybrid graphics switching into any runtimes older than Direct3D 9. I think the only solution is to use a wrapper that wraps to Direct3D 9 or newer.

**Comment by dwg1957** [comment]
You should be able to force the switch through the Nvidia utilities. If I recall correctly there are settings in Windows as well for this somewhere. My desktop does have both, but it is not a hybrids set up naturally.

**Comment by dwg1957** [comment]
I thought I had captured a note about this, I have now found it. It is attached.

[Forcing an Application to use a Nvidia GPU on a Notebook.pdf](https://github.com/user-attachments/files/27421249/Forcing.an.Application.to.use.a.Nvidia.GPU.on.a.Notebook.pdf)

**Comment by BeepBoopWiggleWiggle** [comment]
Thanks, that was my initial approach, but it had no effect.

**Comment by elishacloud** [comment]
The Nvidia Control Panel only works for DX9 and newer games.

**Comment by dwg1957** [comment]
G'day,

I am looking for ideas of potentially things I could try to work around a problem.

One of the options in Links is a Green Analyser, it allows you to see green breaks better. It is a pop up Window.

The problem I have is it often works on the first use, but on the second use more often than not Links just hangs, there is no error, nothing in the event viewer, all I can really do is terminate Links, which will then restart where it left off.

I have no idea if there is anything I can try to see if I can remedy the issue.

On another Windows system without DDrawCompat and an Nvidia HBA, there is no problem.

Any suggestions welcome.

**Comment by narzoul** [comment]
Enable LogLevel=debug in the config, and when the process hangs, also create a crash dump for it from Task Manager (right click on the process -> "Create memory dump file"), then attach both the dump and the log file (compressed).

**Comment by dwg1957** [comment]
I've added both files to a single zip file, created separate zip files for each but in both cases all I get is failed to upload.

**Comment by dwg1957** [comment]
Oh it is a size problem by the looks of it.

**Comment by dwg1957** [comment]
You can copy the zip from my dropbox

https://www.dropbox.com/scl/fi/gvdr9vmvpn2a4kiq801ef/Links_hang.zip?rlkey=i90wnid3ikwp585jrp3c1yken&dl=0

**Comment by narzoul** [comment]
Thanks! I don't see anything suspicious from DDrawCompat's side either in the crash dump or the logs. There is no obvious deadlock, the main thread in the game's executable simply stopped submitting any DirectDraw commands at some point.
I suspect it's a game logic bug and can't be fixed from a wrapper.

**Comment by dwg1957** [comment]
Thanks for checking, Guess I'll put it down to something about NVidia Links likes.

Links has always tended to get on best with Nvidia GPUs and worst with Intel.

**Comment by dwg1957** [comment]
Another question if I may.

In the Links top camera view there is an option to highlight the hole, with this selected it is expected that you will see the hole with a blue line around it. This is not happening with DDrawCompat.

Any ideas?

Thanks

**Comment by narzoul** [comment]
> In the Links top camera view there is an option to highlight the hole, with this selected it is expected that you will see the hole with a blue line around it. This is not happening with DDrawCompat.

Does that mean it's working without DDrawCompat? I can't see it natively, or with dgVoodoo 2 or WineD3D either. Do you have a working setup for comparison?

**Comment by dwg1957** [comment]
I have a few systems that give the expected result.

The first one is a Windows 11 system, it uses no wrapper, but has an Nvidia HBA. Links only really requires a wrapper on my systems under Windows when I only have an Intel GPU.

The second example is from a Linux Systems with Links running under Wine, it does have an Intel GPU but works fine.

The Top camera view is the small window on the right hand side, there is a blue line around the hole's perimeter, this is what I am referring to.

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/232cf34a-4bcd-4b14-9704-cb972a73ebf3" />
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/05c1adbb-6333-482c-9d23-dff9e2587d06" />

**Comment by narzoul** [comment]
Ok, so I guess I misunderstood what "hole" means in this context, as I was looking for a highlight literally around the tiny hole where the ball goes at the end of the course. But in a golf context it seems "hole" can mean the whole "course" too...

The problem was introduced by commit 0fca27fe3cfa12de0b6d803daa1e361d7c210d48. I had a similar issue already fixed in #585, but the patch for that doesn't seem to work here. I'll look into it later.

**Comment by dwg1957** [comment]
Apologies, I play golf in real life so I speak as a golfer with a golfers understanding.

It comes down to the context. 

In this case it is the area from the tee to the green that defines the boundary that encompasses one of the holes on a golf course.

**Comment by narzoul** [comment]
I found the issue. This patch should fix it: [ddraw.zip](https://github.com/user-attachments/files/30049913/ddraw.zip) ([diff.txt](https://github.com/user-attachments/files/30049919/diff.txt) compared to v0.7.1)

**Comment by dwg1957** [comment]
Yes that got the blue line boundary back, but I have a corrupted golfer, corrupted menus etc:

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/f4d607e2-fbeb-4221-b838-38626600b561" />

**Comment by narzoul** [comment]
Huh? I can't reproduce that on any of my 3 GPUs, nor can I imagine how such a small change would cause that. Can you share your DDrawCompat and game config? Is this happening with the main v0.7.1 release too?

**Comment by dwg1957** [comment]
I'm using the version of ddraw that was posted in this thread on Jan 30. 

I've had very few problems with this release, pretty standard changes we do with Links for AA & AF.

VertexFixup was changed to correct a problem rendering one course that I posted a picture of earlier in this thread. SpriteDetection for some corruption in the Top camera view and sub window borders with Intel GPUs.

I've attached DDrawCompat's ini file and Links' System Information screen. This is Links 2003 with the V1.07 update, amongst other things this update gives widescreen support and support for larger textures that are using in many of todays courses.

[DDdrawCompat_config.txt](https://github.com/user-attachments/files/30110395/DDdrawCompat_config.txt)
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/48f29559-44ba-4af2-ab65-8c3c6c2cb5b1" />

**Comment by dwg1957** [comment]
An update.

I created a new DDrawCompat.ini file and set everything to default.

The corruption is no longer present.

I will need to see if I can find my old notes to determine what courses I was having problems with and retest.

**Comment by dwg1957** [comment]
I'm getting some screen flashing at times so something is not quite right.

Also this build has lost the use of Translucent shadows.

P.S. This is golfer translucent shadows, it was fixed in one of the DDraw downloads provided in this thread.

**Comment by dwg1957** [comment]
It appears the newer versions of ddraw.dll gets unhappy with the settings I was using for the previous version. After a reboot with default settings it has been much happier.

The only setting I have so far changed is VertexFixup, this is to correct an artifact on a recently tested course that I could remember.

I do know the other settings I have been using up to now are:

  Antialiasing            = msaa8x(7)
  MouseSensitivity    = native
  SpriteDetection      = point
  TextureFilter           = af16x

I am now, with the newer ddraw, not seeing the problem I was using SpriteDetection for. That problem was corrupted borders in embedded sub windows and also stray lines in the top camera view.

As I said in my earlier post the last version of ddraw.dll corrected the problem that translucent golfer shadows were not working, that issue seems to be back.

**Comment by narzoul** [comment]
Ok, I combined the last 2 patches in this thread: [ddraw.zip](https://github.com/user-attachments/files/30149386/ddraw.zip) ([diff.txt](https://github.com/user-attachments/files/30149389/diff.txt) compared to v0.7.1)

I tested it on all 3 of my GPUs but couldn't reproduce any of the graphical issues you mentioned since the last patch, even though I used the config file you attached earlier.

**Comment by dwg1957** [comment]
I'll give it a try.

I have been trying various settings with the patch I had. So far if I set TextureFilter to af16x, the screen goes black, after killing Links if I then start it again I get the sort of corruption shown in the earlier screen shot. Only a reboot will correct it.

If it makes any difference the system I am using for testing has an Intel Iris Xe embedded GPU in it.

**Comment by dwg1957** [comment]
I just did a very quick test.

Translucent shadows are back and I have the blue hole boundary.

I'll do some more testing when I get the opportunity and see if I can narrow down any graphical glitches better.

Thank you for your efforts, I appreciate it.

**Comment by dwg1957** [comment]
It looks like if I set TextureFilter to af16x I get the image problems with this version of DDrawCompat on my system, this setting was fine with the first posted update that corrected translucent golfer shadows.

I have tried a setting of af8x and have been using Links without problems. 

I have also tried adding an Antialiasing setting of msaa4x(7) again without problems. As far as I can tell there does not seem to be any degradation of the displayed image from using the older version with the higher settings, I did try the higher setting of msaa8x(7) and did not see any problems, but I did not detect any improvement in the images displayed either.

As it stands I have stability and I also now have the blue hole boundary line. 

DDrawCompat with an Intel GPU is very close to the capability we have when using an Nvidia HBA.

Thank you.

**Comment by narzoul** [comment]
To be honest, I have no clue what to do with this. af16x and af8x are identically handled in DDrawCompat, these are just simple numeric parameters sent to the driver (16 vs 8). It shouldn't cause such severe graphical glitches unless there is some serious underlying driver bug. I can't reproduce it on any of my GPUs.

Moreover, it makes no sense how the very simple patch for the hole outline would cause this problem, while it wasn't there in v0.7.1. It has nothing to do with anisotropic filtering.

**Comment by dwg1957** [comment]
As it so happens I cannot reproduce the problem now either. I cannot explain it.

The driver I am somewhat locked in. I did try the generic Intel drivers on the system but they caused problems so I had to go back to using the ASUS provided driver.

**Comment by elishacloud** [comment]
> To be honest, I have no clue what to do with this. af16x and af8x are identically handled in DDrawCompat, these are just simple numeric parameters sent to the driver (16 vs 8). It shouldn't cause such severe graphical glitches unless there is some serious underlying driver bug. I can't reproduce it on any of my GPUs.

I've seen this on my Intel GPU.  For some games if I put more than 8x then the game messes up.  Not sure why, but it seems like some Intel GPUs can't properly handle anything larger than 8x in some cases.  I don't remember the cases though...

Note: On the same device, if I just use the hybrid GPU (Nvidia) then everything works fine for both 8x and 16x.

In my case I think (though I can't prove it) that the Intel GPU can only handle 8x but it still reports 16x as supported.  Maybe this is because the hybrid Nvidia GPU does support 16x?

**Comment by BeepBoopWiggleWiggle** [comment]
I think when DDrawCompat requests 16x, the Intel driver’s legacy translation layer calculates address offsets incorrectly. It essentially tries to fetch texture coordinates out of bounds, leading to visual corruption?

**Comment by dwg1957** [comment]
My testing has come to a halt. After working yesterday I cannot start Links on my Notebook with DDrawcompat, I get a DDERR_SURFACELOST error or if it does come up Links says there is no hardware with 3D acceleration.

It does work with dgVoodoo.

My Desktop which has a Nvidia HBA in it gives the same error with DDrawCompat or indeed with no wrapper at all now, again it works with dgVoodoo. I had tried DDrawCompat on the desktop to see if I could resolve a previous issue of Links being slow when the wrapper was installed, which I did.

It's odd.

**Comment by BeepBoopWiggleWiggle** [comment]
dgVoodoo likely avoids the issue because it translates the calls rather than relying on native legacy Direct3D (like DDrawcompat). On a side note, the latest Windows 11 update seems to have broken backward compatibility across several of my older apps that required legacy DirectX.

**Comment by narzoul** [comment]
> I've seen this on my Intel GPU. For some games if I put more than 8x then the game messes up. Not sure why, but it seems like some Intel GPUs can't properly handle anything larger than 8x in some cases. I don't remember the cases though...

Well, I would understand if the GPU or the drivers can't handle 16x, but then why does it sometimes work and sometimes not?

> My testing has come to a halt. After working yesterday I cannot start Links on my Notebook with DDrawcompat, I get a DDERR_SURFACELOST error or if it does come up Links says there is no hardware with 3D acceleration.
>
> It does work with dgVoodoo.
>
> My Desktop which has a Nvidia HBA in it gives the same error with DDrawCompat or indeed with no wrapper at all now, again it works with dgVoodoo. I had tried DDrawCompat on the desktop to see if I could resolve a previous issue of Links being slow when the wrapper was installed, which I did.
>
> It's odd.

Could you please share the DDrawCompat logs with LogLevel=debug from both systems?

**Comment by elishacloud** [comment]
> Well, I would understand if the GPU or the drivers can't handle 16x, but then why does it sometimes work and sometimes not?

I don't think that is true.  I'm not sure if 16x ever works right on my Intel GPU.  I don't have a chance to test it now, but what might be happening is that the Intel GPU fails when creating a device at 16x but succeeds when creating a render target (and/or zbuffer) surface at 16x.  Or, the other thing that may be happening is if you query CheckDeviceMultiSampleType() it fails at 16x but then it still lets you create a device at 16x.

**Comment by narzoul** [comment]
> I don't think that is true. I'm not sure if 16x ever works right on my Intel GPU. I don't have a chance to test it now, but what might be happening is that the Intel GPU fails when creating a device at 16x but succeeds when creating a render target (and/or zbuffer) surface at 16x. Or, the other thing that may be happening is if you query CheckDeviceMultiSampleType() it fails at 16x but then it still lets you create a device at 16x.

Huh? I was talking about anisotropic filtering, not antialiasing. I don't know of any GPU that supports 16x MSAA, so it's not even an option in DDrawCompat.

**Comment by elishacloud** [comment]
> Huh? I was talking about anisotropic filtering, not antialiasing. I don't know of any GPU that supports 16x MSAA, so it's not even an option in DDrawCompat.

Oh, sorry.  I was confused.

**Comment by BeepBoopWiggleWiggle** [comment]
It seems Intel GPU's have issues with anisotropic filtering settings using DirectX 9 and earlier, so that may be why some games work and others not.

**Comment by dwg1957** [comment]
This is a debug log from my notebook. I also captured the Windows text dump included, if it is of any use.

At best Links will start, sometimes, but Hardware Rendering is turned off, and hardware rendering is a requirement, the program will not work with software rendering.

[Links_Windows_Dump.txt](https://github.com/user-attachments/files/30330386/Links_Windows_Dump.txt)

https://www.dropbox.com/scl/fi/12bz7c4d4j4wnc3dax3b4/Notebook_DDrawCompat-LINKSMMIII.log?rlkey=gzjvj44wqpt7vgocz9o0t5l5r&dl=0

**Comment by dwg1957** [comment]
These are the same files from my desktop

https://www.dropbox.com/scl/fi/qg3liwcejvimluux92les/Desktop_DDrawCompat-LINKSMMIII.log?rlkey=pz8txk5kjy30ls8e17ef58mri&dl=0

[Desktop_Links_Error,txt.txt](https://github.com/user-attachments/files/30332395/Desktop_Links_Error.txt.txt)

**Comment by dwg1957** [comment]
I rolled back my notebook to a restore point about a week back, that seems to have fixed it.

For some reason the desktop only has one rollback point and it is only a few days back, alas that did not help.

Removing and reinstalling Links did not help nor did reinstalling the Nvidia driver. 

I'm at a loss of what to do, clearly something has happened to the system, I would think something has been changed or a file replaced, but what I have no idea, I have not added any new software for some weeks. A full system rebuild would be quite an undertaking especially given this is my core system.

**Comment by narzoul** [comment]
Strange, according to your logs it looks like DirectDraw itself destroys all video memory surfaces a short time after there is a display mode change, which causes the later DDERR_SURFACELOST error. Usually DirectDraw only does this when it detects that the display configuration changed. But the point where this happens makes no sense, since the display mode change already finished successfully earlier and there were even some successful ddraw function calls afterwards that didn't detect any additional mode change. Maybe something is forcing an additional display mode change externally?

In my logs there is only one display mode change made by the game when it starts up, and it restores the original mode only when the game exits. But in yours, it sets the display mode at startup, then restores the original, then sets it and restores it again, and leaves it like that, which doesn't make any sense. Are you trying to play in windowed or fullscreen mode? If windowed, why is there any display mode change at all? If I set the game to windowed mode, I don't have any mode changes at all in my logs.

Also, your game is trying to change the display mode to 1920x1080, but there is no such setting available in the game's display mode list. The maximum is 1440x900 for me. How did you set it up?

I added some extra logs to try to narrow it down, plus I made it crash whenever DirectDraw is destroying the primary surface unexpectedly, which could provide some useful stack trace too.
Please try this version with LogLevel=debug and CrashDump=full:
[ddraw.zip](https://github.com/user-attachments/files/30370768/ddraw.zip) ([diff.txt](https://github.com/user-attachments/files/30370771/diff.txt) compared to v0.7.1)

Please upload both the .log and the .dmp file (if it does crash).

Since your laptop is working now, a log file with this new version from there could be useful as comparison too.

**Comment by dwg1957** [comment]
The startup behaviour is strange for Links, it looks fine to start with then you get a sort of Windows border with a black screen then I get a lot of beeping and sometimes I get the Links main window and sometimes I don't, if I do get the main window Hardware acceleration is disabled.

I use Links in Full screen mode, so I have seen sort of an intermediate mode with the border then it quickly goes into full screen mode. The screen's resolution is 1920 x 1080 so it switch into borderless mode. The standard Links 2003 kit has a top resolution of 1280 x 1024. The 1.07 patch added more resolutions including what you have, the Links graphics display section does not always report correctly but the display shown by the System Info button should be correct. The top resolution with the 1.07 update is 1920 x 1200, we set it by changing an entry in the registry. I've attached a table with the valid values.

The path is:

HKEY_CURRENT_USER
 Software
   Microsoft
     Microsoft Games
       Links 2003
         DisplaySettings 

The value to change is Mode.

<img width="642" height="478" alt="Image" src="https://github.com/user-attachments/assets/00b2fbbd-68e3-45ed-a534-97e83e0f5175" />

I have downloaded the debug version. 

This is the log from the notebook, I zipped it to make it a bit more manageable.

https://www.dropbox.com/scl/fi/h3vztpxmz0vrpte435rrf/Notebook-DDrawCompat-LINKSMMIII.zip?rlkey=j6ulw70avgbnjmky0hildkh0s&dl=0

**Comment by dwg1957** [comment]
The behaviour on the desktop with the debug version is different, the software does its initial start, it does not get as far before giving a standard message that you may be having trouble with 3D Acceleration.

Log file is  at:

https://www.dropbox.com/scl/fi/zhps012ru9ec95ncff9dj/Desktop_DDrawCompat-LINKSMMIII.zip?rlkey=mb2hge8t2pbzmjbo4ja8iiqwl&dl=0

**Comment by narzoul** [comment]
Ah, you didn't set CrashDump=full correctly (there is an extra ":" after "full"), but it doesn't matter. The log does show that there is some external display mode change I can't explain, happening both before and after the game itself changes the display mode. Weird.

The following procedure might reveal what process is responsible for this:

Unzip this file into an empty directory, e.g. into "C:\tmp": [Win32kDisplay.zip](https://github.com/user-attachments/files/30376855/Win32kDisplay.zip)
Open an administrative command prompt (In the start menu, type cmd and press ctrl+shift+enter).
Navigate to the empty directory in the command prompt with this command:
`cd \tmp`
Start an ETW trace session with this command:
`wpr -start Win32kDisplay.wprp!Win32kDisplay -filemode`
Reproduce the issue, then stop the trace with this command:
`wpr -stop Win32kDisplay.etl`

Now there should be a Win32kDisplay.etl file in the same directory, zip it and attach here.

**Comment by dwg1957** [comment]
I did as requested, I still had your debug copy of ddraw.dll in the Links folder, hope that was the intent

The File can be found at

https://www.dropbox.com/scl/fi/r3xib9s6lidejgouk5y5d/Win32kDisplay.etl?rlkey=69e7zldx6tvmqelq7rw7jigpm&dl=0

**Comment by dwg1957** [comment]
Unfortunately my notebook will not start Links today, same symtoms as the desktop. After using the restore point I have not installed anything myself.

There are no newer restore points.

However I can see 4 applications that have yesterday as the date for their install date, these are:

Visual C++  2015-2022 Redistributable X64 14.44.35211.0

Visual C++  2015-2022 Redistributable X86 14.44.35211.0

Edge 150.0.4078.83

Dropbox 262.4.3183

**Comment by narzoul** [comment]
> I did as requested, I still had your debug copy of ddraw.dll in the Links folder, hope that was the intent
> 
> The File can be found at
> 
> https://www.dropbox.com/scl/fi/r3xib9s6lidejgouk5y5d/Win32kDisplay.etl?rlkey=69e7zldx6tvmqelq7rw7jigpm&dl=0

Thanks! Do you still have the debug logs and the crash dump for this run? If not, could you please rerun and add those as well along with the new etl trace? (Note: fix the CrashDump=full setting in your config first first)

**Comment by dwg1957** [comment]
I had the desktop on and had not changed anything, so changed  ini file so Crashdump = full and started Links

There is a file DDrawCompat-LINKMMIII.log, however it is empty.

Latest zipped log file:

https://www.dropbox.com/scl/fi/5cmuvmecpzj89psfsruj1/Desktop_DDrawCompat-LINKSMMIII.zip?rlkey=3dn9xp0wxmylf66jgqfg5coop&dl=0

**Comment by narzoul** [comment]
It looks like the crash dump collection fails with ERROR_INVALID_PARAMETER (0x57). Let's remove the CrashDump setting then, in case that's what's interfering with the log collection too.

Please retry the trace and debug log collection without the CrashDump setting, and share the trace and log file from the same run. Thanks!

**Comment by dwg1957** [comment]
Crashdump setting removed, with this version of ddraw.dll, it tries to start than takes me to the Links message that there is no hardware acceleration, with the other build it seems to be trying to go further with starting Links, I then get screen flashing etc,

https://www.dropbox.com/scl/fi/bwh6orq904m3nv5p1xw0m/DDrawCompat-LINKSMMIII.zip?rlkey=ax4xopzm0j77tbnlc279d2cau&dl=0
 
https://www.dropbox.com/scl/fi/63lf5ynktmcftcpjbesxv/Win32kDisplay.zip?rlkey=hxxu4s7178bpg8z8baaq2hp25&dl=0

**Comment by narzoul** [comment]
Thanks! This is very useful info so far. Could you please also collect debug logs after changing the game's resolution (in the registry) to something other than 1920x1080? No need to bother with the ETW trace, just the debug logs will be enough.

**Comment by dwg1957** [comment]
Sure, that is easy enough to do.

What you have is set as Mode 14

I have changed it to Mode 5 which is compatible to the monitor I have as it has the same aspect ratio.

https://www.dropbox.com/scl/fi/p4up50ojojxzmzk2nkl7c/Desktop_Mode_5_DDrawCompat-LINKSMMIII.zip?rlkey=xiyrvgjbmd45ftqslucribs2g&dl=0

**Comment by narzoul** [comment]
I added a few more debug logs. Please run the game again with both mode 5 and mode 14 using this version, and share the debug logs:
[ddraw.zip](https://github.com/user-attachments/files/30388112/ddraw.zip) ([diff.txt](https://github.com/user-attachments/files/30388113/diff.txt) compared to v0.7.1)

Also, if you check your Windows Update history, are there any updates you installed since the last time the game worked correctly on your desktop?

Thanks!

**Comment by narzoul** [comment]
I forgot an important detail: for the mode 5 test, please set DisplayResolution=app in the DDrawCompat config. The mode 14 test does not need this.

**Comment by dwg1957** [comment]
The last Windows update was July 15. After the problem began I uninstalled Links then installed it again, I also reinstalled my Nvidia driver. I though Links registry may have been a problem, did not expect much from reinstalling Nvidia.

A number of other programs are showing installed dates since the issue began:

Google Play Games - I never installed this so I imagine Acer must have 
Microsoft Edge

Logs are at:

https://www.dropbox.com/scl/fi/6508zzxxvv6mll4jxt8ty/Mode_4_DDrawCompat-LINKSMMIII.zip?rlkey=b7skt25bjsslb7zhmfl925vc5&dl=0

https://www.dropbox.com/scl/fi/odguolr8gxbkrwzr4cdxy/Mode_14_DDrawCompat-LINKSMMIII.zip?rlkey=sar24dmo5b50lhc7z1v5ebz6u&dl=0

**Comment by narzoul** [comment]
This is getting more and more weird. According to the logs, DDrawCompat cannot open the DWM_DX_FULLSCREEN_TRANSITION_EVENT object on your system, which means the native ddraw.dll would fail to open it too.

What is the file version and file size of C:\Windows\SysWOW64\ddraw.dll on your system?

**Comment by dwg1957** [comment]
Now that is interesting.

On my desktop, as it has an Nvidia HBA it never needed a wrapper before, I think I said my desktop gets the same error when I do not have a wrapper installed. If something changed this file that would account for it not working

I've located the ddraw.dll file it is 539,648 bytes in size and its dated 15/4/2026

File version shows as 10.0.26100.8115, product version is the same

<img width="401" height="510" alt="Image" src="https://github.com/user-attachments/assets/3373a337-aab5-468f-bbd4-014072042e69" />

**Comment by narzoul** [comment]
Hmm, that's the exact same version as I have, so it should be using the same event object name.

Please download the WinObj tool from Sysinternals: https://learn.microsoft.com/en-us/sysinternals/downloads/winobj
Unzip it, right-click on Winobj.exe in File Explorer and select "Run as Administrator" from the popup menu.
In the tool, open "Find/Search..." in the top menu and search for the string "DWM".

In my case, the results look like this:
<img width="673" height="338" alt="Image" src="https://github.com/user-attachments/assets/c0ac1232-2e4c-4e96-80b8-313d8ba71d7a" />

Does it find DWM_DX_FULLSCREEN_TRANSITION_EVENT for you?

**Comment by dwg1957** [comment]
This is what I get

<img width="600" height="340" alt="Image" src="https://github.com/user-attachments/assets/dda388a1-cafc-4495-be54-b7949899437c" />

**Comment by narzoul** [comment]
I've added some extra logs to find out why the event can't be opened: [ddraw.zip](https://github.com/user-attachments/files/30408952/ddraw.zip) ([diff.txt](https://github.com/user-attachments/files/30408961/diff.txt) compared to v0.7.1)

Please run this with LogLevel=debug using mode 14 and share the debug logs. Thanks!

**Comment by dwg1957** [comment]
Log file is:

https://www.dropbox.com/scl/fi/guz6ge78t1lddcm1bzz3s/DDrawCompat-LINKSMMIII.zip?rlkey=fr2honhvwbyk3k30whdcfli8f&dl=0

**Comment by narzoul** [comment]
Both DDrawCompat and native ddraw fail to open the event with ERROR_ACCESS_DENIED (0x5).

I have an idea based on this Vogons thread: https://www.vogons.org/viewtopic.php?t=72774
It suggests that Process Hacker can change the permissions on the event object.
Note that Process Hacker has since been renamed to System Informer. It can be downloaded here:
https://systeminformer.com/downloads
I personally chose the Binaries (Portable) format.

Run amd64\SystemInformer.exe as Administrator and double click on dwm.exe in the process list (you can type "dwm" in the search box in the top right corner to find it faster).
Click on the Handles tab and put DWM_DX_FULLSCREEN_TRANSITION_EVENT in the search box. It should give one result. Double click on that.
Go to the Security tab and click the Edit button.
Take a screenshot of the group names and permissions for each group and post it here. I assume the permissions look the same for all groups, so one screenshot of the window should be enough.
Click the Add button, put "Everyone" in the the text box and click OK. Now "Everyone" should show up in the list, with "Permission for Everyone" showing a tick in the "Allow" column for "Full control", "Query" and "Modify".
Delete all of the other groups (other than "Everyone") by clicking on them and then clicking on the Remove button.
Click the OK button at the bottom when finished.

Now launch the game again the same way as before and share the debug logs.

The event seems to be created by C:\Windows\System32\dwmcore.dll. Please check and post the version details on that too.

Note: the security permissions will be restored when you restart your PC, so these changes shouldn't be permanent. I verified on my PC that removing all groups reproduces the ERROR_ACCESS_DENIED error, but having only "Everyone" in the list fixes it. So hopefully this works for you too.

Thanks!

**Comment by dwg1957** [comment]
dwmcore.dll size 4,370,430 dated 15/7/2026  version 10.0.26100.8875

https://www.dropbox.com/scl/fi/7hsi7bslbhaqcfdh2qylk/DDrawCompat-LINKSMMIII.zip?rlkey=nb7l87w9onui0kxuekteqtm09&dl=0

**Comment by narzoul** [comment]
The version matches, but for me the size is 4,370,432 bytes. Did you make a typo?

The logs show that the event was opened correctly now. This reintroduces the old buggy 3-second delay after a mode switch to the same mode that the display is already in, which coincidentally fixes the GdiEntry13 issue. There are no more lost surface errors with this. What was the observed behavior? I don't see any suspicious ddraw errors anymore.

Now the better test would be to see if this can be used to detect that extra bump in the GdiEntry13 return value that follows some time after the real mode change. For this, please execute the same test also for mode 5 with DisplayResolution=app, and share the debug logs.
I'm assuming you haven't signed out of your Windows user or restarted your PC yet, so the security fix should still be active. If not, please redo the security fix first on DWM_DX_FULLSCREEN_TRANSITION_EVENT for this test.

**Comment by dwg1957** [comment]
Apologies, yes it was a typo, the size is indeed 4,370,432

The behaviour was that the Links opening screen can be displayed at times before I go back to the system or I get a black screen and then back to the normal display. I tend to try starting the software twice, some changes to Links requires two restarts.

That got me thinking though. The game Icon calls LinksLauncher.exe, the main game is LinksMMIII.exe, I started that directly and it did come up on my desktop, I have not rebooted since the last change. I looked at hardware Acceleration and it is turned on and I can indeed load a golf course, I am pretty sure I tried starting the main program early in the piece and it did not work then, that is one of the standard Links troubleshoot tests 

There is a mystery there somewhere. I have always been able to just use the standard method for starting Links in the past.

Whether it will start after a reboot is another question.

**Comment by dwg1957** [comment]
The answer to that question is that after a reboot it will not start either way, using the standard icon gives me the hardware acceleration message using the program directly just a black screen which then just goes back to my normal Windows display.

**Comment by narzoul** [comment]
Unfortunately starting through the launcher or directly makes no difference on my system. I noticed that you're using Windows XP compatibility mode on LinkMMIII.exe, which doesn't seem necessary (for me at least), but enabling that also doesn't reproduce the issue, with or without the launcher.

The GdiEntry13 behavior is still suspicious. I think the last patch version works around it by coincidence due to the 3-second delay. If you try an earlier version of DDrawCompat like the original combined patch in this thread, or even v0.7.1, I assume it still won't work because of the GdiEntry13 problem. So the test with mode 5 and DisplayResolution=app would still be useful.

Note: since you restarted your system, you'll need to redo the security fix before running the test.

**Comment by dwg1957** [comment]
Which version of DDraw do you want me to try with mode 5 ?

**Comment by narzoul** [comment]
The last patch that I attached here, after the security fix is applied (in case you didn't catch my earlier edit). Post the debug logs as usual.

**Comment by dwg1957** [comment]
Went through the process again, Mode 5. This is the log using LinksLauncher, Using the program directly this time did not work.

I go to a black screen spinning circle then back to the Windows display

https://www.dropbox.com/scl/fi/ozt9neod6rkton6bbh1cg/Launcher_DDrawCompat-LINKSMMIII.zip?rlkey=hc9537j0dsdm6lx5lv0cqgm81&dl=0

**Comment by narzoul** [comment]
Thanks, this at least confirms what I was worried about. Even though DWM_DX_FULLSCREEN_TRANSITION_EVENT now works correctly, it also gets into signaled state before the second mysterious bump in the uniqueness counter returned by GdiEntry13. So waiting on the event also doesn't fix the problem.

At the moment I have no clue how to solve this problem. I'll have to try to find what function is responsible for changing the uniqueness counter to see if we can trace what causes the second change, but I have little hope of finding it without the Windows 11 source code.

The security issue is also puzzling. DWM_DX_FULLSCREEN_TRANSITION_EVENT should be accessible by default. Perhaps some security software on your system is interfering with that? I have no other ideas.

**Comment by narzoul** [comment]
The good news is that I found a way to trace the uniqueness counter increments. The bad news is that it's quite complicated, requiring to set up DTrace: https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/dtrace#installing-dtrace-under-windows

Would you be willing to go through all that?
The steps mention that you should disable "Patchguard, BitLocker and Secure Boot" but I didn't have to do those steps (even though I'm pretty sure I have Secure Boot on), so you can probably skip that.
You can also ignore the mentions of Windows Insider builds, it works just fine on Windows 11 25H2.

Let me know if you're willing to try to set this up, and if the "Validating the DTrace installation" step is successful, or if you run into some problems on the way there.

**Comment by dwg1957** [comment]
I've read it, it does get rather involved.

At the moment I just do not feel that I am up to that, a few things are happening that will be ongoing for a while.

Given it happened on both systems at the same time, I suspect something at the system level happened, especially as an initial restore to an early restore point had it running for that day, only to fail on the next boot, what I have no idea.

For now I have installed dgVoodoo on the desktop, and will have to accept its limitations on both systems, or play Links on Linux where I also have it running, Links does not appear to have any limitations on Linux to speak of. Windows is the preferred platform and I do prefer my Windows desktop overall, my Linux systems are older retired Windows systems.

If I get too annoyed no doubt I will return to trying this out. I will keep my eyes open for any potential fixes, and will also raise it on the Links Corner forums when it becomes alive again (it is being moved to a new host provider). With Links Corner being down for the last week I cannot see if anyone else has had the problem as that is where most problems are raised. I bought it up here as I initially had the problem on my notebook with the DDrawCompat wrapper, and with its Intel GPU, I have to use a wrapper. It was only after some initial troubleshoots I tried the older wrapper, I initially had it on that machine so had a preconfigured copy I could try. 

Thanks for the assistance.

**Comment by dwg1957** [comment]
I thought I would try someone on my notebook. 

I put DDrawCompat back on my notebook, dropped the resolution to a lower level 1808 x 1008 rather than the screens 1920  x 1080 and put Links into Windowed rather than full screen mode and the software runs with hardware acceleration.

I do not know if this gives any indication of what is going on but thought I would note it.

**Comment by narzoul** [comment]
Windowed mode doesn't require any display mode changes at all, so it probably bypasses the problem entirely. Whatever is happening on your systems happens shortly after the game changes the display mode, which only happens in fullscreen mode.

I was thinking I could effectively bypass the display mode change in fullscreen mode as well, assuming that you always use DisplayResolution=desktop and DisplayRefreshRate=desktop. But not everyone wants to use DisplayResolution=desktop, so this still doesn't really solve the problem, just works around it with some specific forced settings. I'd rather find out what's really going wrong with the display mode change.

**Comment by dwg1957** [comment]
Thank you for the explanation.

I have tried the same approach on my desktop where it also works with no wrapper in use, but an Nvidia GT1030 HBA is in place, the unfortunate thing there is that text is rather blurred for some reason.

I have just seen another post where a user has replaced his MLB and CPU and is getting the same error under Windows 11, the use of Windowed mode is also working for him.

**Comment by narzoul** [comment]
Can you try renaming LinksMMIII.exe to something else and run the game from the renamed exe? It might get rid of some Windows compatibility settings and GPU driver profiles that could be interfering.

If the other user can run DTrace, that could also be very useful.

**Comment by dwg1957** [comment]
I copied LinksMMIII.exe to another name and tried running it, it gives the same result, no change.

I just saw the mentioned posted, these do not get emailed, it does sound to be something along the same lines, the timing is a little different.

I know that Links was working on July 19. It definately failed on July 23, whether I played Links in the interveniening days and on what machines I cannot say - I also have Links running on Linux.

**Comment by dwg1957** [comment]
FWIW installing DDrawCompat on my desktop corrected the Text issue. So while lacking the ideal Full screen mode at the moment I do have a functioning system.

**Comment by narzoul** [comment]
@dwg1957 Please check the update here: https://github.com/narzoul/DDrawCompat/issues/614#issuecomment-5576067705

If you'd like to keep your color profiles, you don't have to go through with any of that. Probably I can work around the problem in DDrawCompat. I'll post a tentative patch tomorrow.

**Comment by dwg1957** [comment]
As far as I can recall I've never even looked at colour profiles, with my computer use and needs I cannot see that I would need them so I will take a look at the other thread.

**Comment by dwg1957** [comment]
No good new here I am afraid.

I concentrated on my desktop machine.

It took a couple of goes to remove the colour profiles it did have one for my LG monitors, but they were finally removed, and the systems now shows no profiles found.

I removed DDrawCompat and went back to my original configuration of 1920 x 1080 full screen mode, this is the monitors native resolution, with no wrapper..

Tried it a couple of times but I still get the same surface lost error.

Reinstated DDrawCompat - the Links specific version, left the configuration as it was otherwise and tried again, sill get the surface lost error.

Took it back to Windowed mode with 1808 x 1008 resolution and it is working again.

So it really made no difference.

**Comment by narzoul** [comment]
Test fix for the color profile issue, including the 2 previous patches: [ddraw.zip](https://github.com/user-attachments/files/32071277/ddraw.zip) ([diff.txt](https://github.com/user-attachments/files/32071279/diff.txt) compared to v0.7.1)

**Comment by dwg1957** [comment]
I have install the latest ddraw.dll file on both my desktop and notebooks, Both run Windows 11 the Desktop is a Gen13 i5 with an Nvidia GT1030, the notebook is a Gen 11 i5 with Intel iRIS xe onboard graphics.

In both case I reset Links to the native 1920 x 1080 resolution in full screen mode.

I played a few holes on each machine on two different courses and it worked without problem.

Thank you for your efforts, it is much appreciated.
