### ISSUE TITLE
Midtown Madness 1

### ISSUE THREAD

**Issue by midtown96** [narzoul/DDrawCompat#97]
I put th ddraw.dll from DDrawCompat v0.3.0 to the same folder as midtown.exe and renamed midtown.exe to midtownmadness.exe and the game starts but when I try to load a race, the game crashes. Sometimes the race will start but wen I click quit to race menu the game crashes. I have even tried the compatibility properties and nothing works. I have windows 10 64 bit

Please help!

**Comment by narzoul** [comment]
Hmm, no crashes here. Are you using some mods/patches?
Please use the ReleaseWithDebugLogs build in the debug zip file and make it crash with that, then attach the logs here (compressed, if possible).

**Comment by midtown96** [comment]
Here is the logs compressed.
[DDrawCompat-midtownmadness.zip](https://github.com/narzoul/DDrawCompat/files/6451315/DDrawCompat-midtownmadness.zip)

**Comment by narzoul** [comment]
Thanks! It's probably the same issue as https://github.com/narzoul/DDrawCompat/issues/96. I'll try to release a new version with a fix this week.

**Comment by narzoul** [comment]
Fixed in v0.3.1.

**Comment by midtown96** [comment]
Thanks!
The new fix works fine for mm1 but in mm2 I still cant see the introvideo.
Is it any problems with introvideos?
Sorry for I forgot to tell you that with introvideos when I told you about the problem with mm1.
